#!/usr/bin/env python3
"""Generate V48 — Domex weight-based courier pricing + per-item courier switch + faraway cities.

Sources (owner 2026-07-16):
  - "DELIVERY RATES" rate card image: per-board weight rates (1st kg / additional kg) with
    CITY LIMITS & SUBURBS sharing one weight rate, OUTSTATION and FARAWAY their own; plus a
    per-package handling fee for packages above 2 ft, per area.
  - "FARAWAY CITIES.xlsx": Domex's current faraway city list (name -> FARAWAY courier band).
    Zero collisions with non-FARAWAY names already seeded by V32 (verified at generation time).

Emits committed SQL; the script is a dev tool and never runs in prod.
"""

from __future__ import annotations

import re
import unicodedata
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
ROOT = Path(__file__).resolve().parents[2]
XLSX = ROOT / "FARAWAY CITIES.xlsx"
OUT = Path(__file__).resolve().parents[1] / "src/main/resources/db/migration/V48__courier_weight_rates.sql"

# LKR cents. CITY LIMITS & SUBURBS share the weight rate; handling differs per area.
RATES = [
    # zone,        first kg, add'l kg, handling per package above 2 ft
    ("CITY_LIMITS", 38000, 18000, 75000),
    ("SUBURBS",     38000, 18000, 100000),
    ("OUTSTATION",  50000, 20000, 150000),
    ("FARAWAY",     65000, 25000, 200000),
]


def normalize(s: str) -> str:
    s = unicodedata.normalize("NFD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    return re.sub(r"[^a-z0-9]+", "", s.lower())


def read_cities() -> list[str]:
    z = zipfile.ZipFile(XLSX)
    try:
        ss = ET.fromstring(z.read("xl/sharedStrings.xml"))
        strings = ["".join(t.text or "" for t in si.iter("{%s}t" % NS["m"])) for si in ss.findall("m:si", NS)]
    except KeyError:
        strings = []
    root = ET.fromstring(z.read("xl/worksheets/sheet1.xml"))
    names: list[str] = []
    for row in root.iter("{%s}row" % NS["m"]):
        for c in row.iter("{%s}c" % NS["m"]):
            v = c.find("m:v", NS)
            val = strings[int(v.text)] if (v is not None and c.get("t") == "s") else (v.text if v is not None else "")
            val = re.sub(r"\s+", " ", (val or "")).strip()
            if val:
                names.append(val)
    # everything after the "Faraway Cities" marker row is a city name
    start = next(i for i, n in enumerate(names) if n.lower() == "faraway cities") + 1
    return names[start:]


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    cities = read_cities()
    seen: set[str] = set()
    rows: list[tuple[str, str]] = []
    for c in cities:
        n = normalize(c)
        if not n or n in seen:
            continue
        seen.add(n)
        rows.append((n, c))
    assert len(rows) > 800, f"faraway list suspiciously short: {len(rows)}"

    lines = [
        "-- V48 — Domex weight-based courier pricing (owner 2026-07-16 rate card) + per-item courier",
        "-- switch + the courier's current faraway city list. Generated by",
        "-- backend/scripts/generate_courier_weight_migration.py. Money in integer LKR cents.",
        "",
        "-- Per-item courier availability (loosely coupled, like the per-zone lorry switches of V35):",
        "-- effective value is product AND variant. Which items actually keep the courier is data,",
        "-- seeded by V49.",
        "ALTER TABLE product ADD COLUMN courier_enabled BOOLEAN NOT NULL DEFAULT true;",
        "ALTER TABLE product_variant ADD COLUMN courier_enabled BOOLEAN NOT NULL DEFAULT true;",
        "",
        "-- Weight-based rate card replaces the flat per-(zone, size-tier) card of V30:",
        "-- per board: first kg + (ceil(weight)-1) x additional kg; packages above 2 ft",
        "-- (board_size_tier <> 'UNDER_2FT') add the area's per-package handling fee.",
        "DROP TABLE courier_rate_card;",
        "CREATE TABLE courier_rate_card (",
        "    zone                    VARCHAR(32) PRIMARY KEY",
        "        CHECK (zone IN ('CITY_LIMITS','SUBURBS','OUTSTATION','FARAWAY')),",
        "    first_kg_cents          BIGINT NOT NULL CHECK (first_kg_cents >= 0),",
        "    addl_kg_cents           BIGINT NOT NULL CHECK (addl_kg_cents >= 0),",
        "    handling_over_2ft_cents BIGINT NOT NULL CHECK (handling_over_2ft_cents >= 0)",
        ");",
        "",
        "INSERT INTO courier_rate_card (zone, first_kg_cents, addl_kg_cents, handling_over_2ft_cents) VALUES",
        ",\n".join(f"    ('{z}', {f}, {a}, {h})" for z, f, a, h in RATES) + ";",
        "",
        f"-- Domex faraway city list ({len(rows)} names; upsert — the courier's list wins for the band).",
        "INSERT INTO courier_area (name_normalized, display_name, courier_zone) VALUES",
    ]
    values = ",\n".join(f"    ({sql_str(n)},{sql_str(d)},'FARAWAY')" for n, d in rows)
    lines.append(values)
    lines.append("ON CONFLICT (name_normalized) DO UPDATE SET courier_zone = 'FARAWAY';")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.name}: {len(rows)} faraway areas, {len(RATES)} rate rows")


if __name__ == "__main__":
    main()
