-- V12 — Wishlist (03-wishlist/plan.md §2). Customer-scoped, RLS-enforced.

CREATE TABLE wishlist_item (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT      NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    product_id  BIGINT      NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_wishlist_customer_product UNIQUE (customer_id, product_id)
);
CREATE INDEX ix_wishlist_customer ON wishlist_item(customer_id);

ALTER TABLE wishlist_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishlist_item FORCE ROW LEVEL SECURITY;

CREATE POLICY wishlist_owner ON wishlist_item
    USING (customer_id = current_setting('app.current_user_id', true)::bigint);

GRANT SELECT, INSERT, UPDATE, DELETE ON wishlist_item TO scanlanka_rls;
GRANT USAGE, SELECT ON SEQUENCE wishlist_item_id_seq TO scanlanka_rls;
