-- V13 — Saved addresses + stock soft-reservations (05-checkout-delivery §2).

CREATE TABLE address (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT      NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    label       VARCHAR(80),
    street      VARCHAR(300) NOT NULL,
    city        VARCHAR(120) NOT NULL,
    province    VARCHAR(120) NOT NULL,
    postal_code VARCHAR(10)  NOT NULL,
    phone       VARCHAR(32)  NOT NULL,
    email       VARCHAR(254) NOT NULL,
    is_default  BOOLEAN      NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_address_customer ON address(customer_id);

ALTER TABLE address ENABLE ROW LEVEL SECURITY;
ALTER TABLE address FORCE ROW LEVEL SECURITY;
CREATE POLICY address_owner ON address
    USING (customer_id = current_setting('app.current_user_id', true)::bigint);

CREATE TABLE stock_reservation (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT      NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    product_id  BIGINT      NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    variant_id  BIGINT      REFERENCES product_variant(id) ON DELETE CASCADE,
    quantity    INTEGER     NOT NULL CHECK (quantity >= 1),
    expires_at  TIMESTAMPTZ NOT NULL,
    released    BOOLEAN     NOT NULL DEFAULT false
);
CREATE INDEX ix_reservation_variant ON stock_reservation(variant_id) WHERE NOT released;
CREATE INDEX ix_reservation_expiry ON stock_reservation(expires_at) WHERE NOT released;
CREATE INDEX ix_reservation_product ON stock_reservation(product_id) WHERE NOT released;

GRANT SELECT, INSERT, UPDATE, DELETE ON address TO scanlanka_rls;
GRANT USAGE, SELECT ON SEQUENCE address_id_seq TO scanlanka_rls;
GRANT SELECT, INSERT, UPDATE, DELETE ON stock_reservation TO scanlanka_rls;
GRANT USAGE, SELECT ON SEQUENCE stock_reservation_id_seq TO scanlanka_rls;
