-- V16 — Refund records (16-returns-refunds). Order row stays immutable; refunds are linked records.
CREATE TABLE refund (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT       NOT NULL REFERENCES "order"(id) ON DELETE RESTRICT,
    amount_cents    BIGINT       NOT NULL CHECK (amount_cents >= 0),
    method          VARCHAR(14)  NOT NULL CHECK (method IN ('PAYHERE','BANK','STORE_CREDIT')),
    reason          VARCHAR(20),
    gateway_ref     VARCHAR(120),
    status          VARCHAR(12)  NOT NULL DEFAULT 'RECORDED'
                      CHECK (status IN ('RECORDED','DONE','FAILED')),
    idempotency_key VARCHAR(120) NOT NULL UNIQUE,
    created_by      BIGINT       NOT NULL REFERENCES app_user(id),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_refund_order ON refund(order_id);

CREATE TABLE refund_item (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id     BIGINT      NOT NULL REFERENCES refund(id) ON DELETE CASCADE,
    order_item_id BIGINT      NOT NULL REFERENCES order_item(id) ON DELETE RESTRICT,
    quantity      INTEGER     NOT NULL CHECK (quantity >= 1),
    disposition   VARCHAR(10) NOT NULL CHECK (disposition IN ('RESTOCK','WRITE_OFF'))
);
