-- V17 — Bulk / international quote requests (11-quote-requests).
CREATE TABLE quote_request (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_name      VARCHAR(160) NOT NULL,
    email               VARCHAR(254) NOT NULL,
    phone               VARCHAR(32)  NOT NULL,
    country             VARCHAR(2),
    message             TEXT,
    status              VARCHAR(14)  NOT NULL DEFAULT 'NEW'
                          CHECK (status IN ('NEW','QUOTED','NEGOTIATING','ACCEPTED','REJECTED','EXPIRED')),
    quoted_total_cents  BIGINT,
    access_token_hash   VARCHAR(100) NOT NULL,
    customer_id         BIGINT       REFERENCES app_user(id) ON DELETE SET NULL,
    expires_at          TIMESTAMPTZ,
    converted_order_id  BIGINT       REFERENCES "order"(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_quote_status ON quote_request(status, created_at DESC);

CREATE TABLE quote_item (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id      BIGINT       NOT NULL REFERENCES quote_request(id) ON DELETE CASCADE,
    product_id    BIGINT       REFERENCES product(id) ON DELETE SET NULL,
    variant_id    BIGINT       REFERENCES product_variant(id) ON DELETE SET NULL,
    name_snapshot VARCHAR(300) NOT NULL,
    quantity      INTEGER      NOT NULL CHECK (quantity >= 1),
    note          VARCHAR(300)
);

CREATE TABLE quote_message (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id           BIGINT      NOT NULL REFERENCES quote_request(id) ON DELETE CASCADE,
    sender             VARCHAR(10) NOT NULL CHECK (sender IN ('ADMIN','REQUESTER')),
    body               TEXT        NOT NULL,
    quoted_price_cents BIGINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
