-- V18 — Contact inquiries (12-contact-whatsapp).
CREATE TABLE contact_inquiry (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(160) NOT NULL,
    email      VARCHAR(254) NOT NULL,
    phone      VARCHAR(32),
    message    TEXT         NOT NULL,
    status     VARCHAR(12)  NOT NULL DEFAULT 'NEW' CHECK (status IN ('NEW','HANDLED')),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_contact_status ON contact_inquiry(status, created_at DESC);

INSERT INTO app_setting (key, value) VALUES
    ('whatsapp_local', '0706307685'),
    ('whatsapp_intl', '0714307685')
ON CONFLICT (key) DO NOTHING;
