-- V1 — Auth baseline (07-auth-accounts/plan.md §2). Foundation referenced by cart/address/order.
-- App connects as a non-superuser, non-BYPASSRLS role (global/02 §6).

CREATE TABLE app_user (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(254) NOT NULL UNIQUE,
    password_hash  VARCHAR(100) NOT NULL,
    name           VARCHAR(160),
    role           VARCHAR(16)  NOT NULL DEFAULT 'CUSTOMER' CHECK (role IN ('CUSTOMER','ADMIN')),
    email_verified BOOLEAN      NOT NULL DEFAULT false,
    token_version  INTEGER      NOT NULL DEFAULT 0,
    totp_secret    VARCHAR(160),
    totp_enabled   BOOLEAN      NOT NULL DEFAULT false,
    status         VARCHAR(12)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','LOCKED')),
    failed_logins  INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- case-insensitive uniqueness on email
CREATE UNIQUE INDEX ux_app_user_email_lower ON app_user (lower(email));

CREATE TABLE one_time_code (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    purpose     VARCHAR(16)  NOT NULL CHECK (purpose IN ('EMAIL_VERIFY','PASSWORD_RESET')),
    code_hash   VARCHAR(100) NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    attempts    INTEGER      NOT NULL DEFAULT 0,
    consumed    BOOLEAN      NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_otc_user_purpose ON one_time_code (user_id, purpose) WHERE NOT consumed;

CREATE TABLE refresh_token (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    token_hash  VARCHAR(100) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT false,
    replaced_by BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_refresh_user ON refresh_token (user_id);
