-- V20 — Homepage merchandising (14-homepage-merchandising).
CREATE TABLE featured_product (
    product_id    BIGINT  PRIMARY KEY REFERENCES product(id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE banner (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_storage_key VARCHAR(512) NOT NULL,
    image_url         VARCHAR(1024) NOT NULL,
    link_url          VARCHAR(1024),
    display_order     INTEGER      NOT NULL DEFAULT 0,
    starts_at         TIMESTAMPTZ,
    ends_at           TIMESTAMPTZ,
    active            BOOLEAN      NOT NULL DEFAULT true,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
