-- V23 — advance the delivery_zone identity sequence past the seeded row.
-- V6 seeded delivery_zone with an explicit id=1, but GENERATED BY DEFAULT AS IDENTITY does not advance
-- its sequence on explicit inserts, so the first admin-created zone would be generated as id=1 and
-- collide on the primary key (HTTP 500 instead of the intended postal-overlap 409).
SELECT setval(pg_get_serial_sequence('delivery_zone', 'id'),
              (SELECT COALESCE(MAX(id), 1) FROM delivery_zone));
