-- V24 — Customer-care live chat (17-customer-care-chat). Token-scoped guest access; admin inbox.

CREATE TABLE support_conversation (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_name      VARCHAR(160),
    visitor_email     VARCHAR(254),
    access_token_hash VARCHAR(100) NOT NULL UNIQUE,
    customer_id       BIGINT       REFERENCES app_user(id) ON DELETE SET NULL,
    status            VARCHAR(10)  NOT NULL DEFAULT 'OPEN'
                          CHECK (status IN ('OPEN', 'CLOSED')),
    page_context      VARCHAR(500),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_support_conv_status ON support_conversation(status, updated_at DESC);

CREATE TABLE support_message (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT       NOT NULL REFERENCES support_conversation(id) ON DELETE CASCADE,
    sender          VARCHAR(10)  NOT NULL CHECK (sender IN ('VISITOR', 'ADMIN')),
    body            TEXT         NOT NULL,
    admin_user_id   BIGINT       REFERENCES app_user(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_support_msg_conv ON support_message(conversation_id, created_at);
