-- V2 — Product catalog (01-product-catalog/plan.md §2). Money in integer LKR cents.
-- Note: the normalized variant_option join is deferred — `options_signature` (sorted price-affecting
-- option ids) is the source of truth for which options compose a variant (and the resolution key).

CREATE TABLE parent_product (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    slug       VARCHAR(220) NOT NULL UNIQUE,
    category   VARCHAR(120),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE product (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_product_id     BIGINT       REFERENCES parent_product(id) ON DELETE SET NULL,
    name                  VARCHAR(200) NOT NULL,
    slug                  VARCHAR(220) NOT NULL UNIQUE,
    sku                   VARCHAR(64)  NOT NULL UNIQUE,
    description           TEXT,
    details               TEXT,
    category              VARCHAR(120),
    price_mode            VARCHAR(16)  NOT NULL CHECK (price_mode IN ('SINGLE','VARIANT')),
    single_price_cents    BIGINT       CHECK (single_price_cents >= 0),
    price_range_min_cents BIGINT,
    price_range_max_cents BIGINT,
    stock_qty             INTEGER      CHECK (stock_qty >= 0),
    weight_kg             NUMERIC(10,3),
    length_cm             NUMERIC(10,2),
    width_cm              NUMERIC(10,2),
    height_cm             NUMERIC(10,2),
    handling_class        VARCHAR(16)  NOT NULL DEFAULT 'STANDARD'
                            CHECK (handling_class IN ('STANDARD','FRAGILE_GLASS','OVERSIZE')),
    active                BOOLEAN      NOT NULL DEFAULT true,
    archived              BOOLEAN      NOT NULL DEFAULT false,
    archived_at           TIMESTAMPTZ,
    promo_eligible        BOOLEAN      NOT NULL DEFAULT true,   -- expansion hook (FR-CATALOG-15)
    attributes            JSONB        NOT NULL DEFAULT '{}',   -- future metadata (unmapped for now)
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT single_price_when_single
        CHECK (price_mode <> 'SINGLE' OR single_price_cents IS NOT NULL)
);
CREATE INDEX ix_product_parent   ON product(parent_product_id);
CREATE INDEX ix_product_active    ON product(active, archived);
CREATE INDEX ix_product_category  ON product(category);

CREATE TABLE product_image (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT        NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    storage_key   VARCHAR(512)  NOT NULL,
    url           VARCHAR(1024) NOT NULL,
    alt_text      VARCHAR(300),
    is_preview    BOOLEAN       NOT NULL DEFAULT false,
    display_order INTEGER       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_image_product ON product_image(product_id, display_order);
CREATE UNIQUE INDEX ux_image_preview ON product_image(product_id) WHERE is_preview;

CREATE TABLE spec_group (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT       NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    name            VARCHAR(120) NOT NULL,
    price_affecting BOOLEAN      NOT NULL DEFAULT false,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    UNIQUE (product_id, name)
);

CREATE TABLE spec_option (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec_group_id BIGINT       NOT NULL REFERENCES spec_group(id) ON DELETE CASCADE,
    value         VARCHAR(160) NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0,
    UNIQUE (spec_group_id, value)
);

CREATE TABLE product_variant (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT      NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    sku               VARCHAR(64) NOT NULL UNIQUE,
    price_cents       BIGINT      NOT NULL CHECK (price_cents >= 0),
    stock_qty         INTEGER     CHECK (stock_qty >= 0),
    weight_kg         NUMERIC(10,3),
    length_cm         NUMERIC(10,2),
    width_cm          NUMERIC(10,2),
    height_cm         NUMERIC(10,2),
    handling_class    VARCHAR(16) CHECK (handling_class IN ('STANDARD','FRAGILE_GLASS','OVERSIZE')),
    active            BOOLEAN     NOT NULL DEFAULT true,
    options_signature VARCHAR(200) NOT NULL,
    UNIQUE (product_id, options_signature)
);
CREATE INDEX ix_variant_product ON product_variant(product_id);
