-- V32 — Citrek courier area definitions (client document, 2026).
-- City name lookup at checkout; postal_zone updated as fallback.

CREATE TABLE IF NOT EXISTS courier_area (
    name_normalized VARCHAR(120) PRIMARY KEY,
    display_name    VARCHAR(200) NOT NULL,
    courier_zone    VARCHAR(32)  NOT NULL
        CHECK (courier_zone IN ('CITY_LIMITS','SUBURBS','OUTSTATION','FARAWAY'))
);

TRUNCATE courier_area;

INSERT INTO courier_area (name_normalized, display_name, courier_zone) VALUES
    ('bambalapitiya','Bambalapitiya','CITY_LIMITS'),
    ('bloemendhal','Bloemendhal','CITY_LIMITS'),
    ('borella','Borella','CITY_LIMITS'),
    ('cinnamongardens','Cinnamon Gardens','CITY_LIMITS'),
    ('colombo','Colombo','CITY_LIMITS'),
    ('colombo115','Colombo 1-15','CITY_LIMITS'),
    ('dematagoda','Dematagoda','CITY_LIMITS'),
    ('fort','Fort','CITY_LIMITS'),
    ('grandpass','Grand pass','CITY_LIMITS'),
    ('havelocktown','Havelock Town','CITY_LIMITS'),
    ('jawatte','Jawatte','CITY_LIMITS'),
    ('kirilapone','Kirilapone','CITY_LIMITS'),
    ('kollupitiya','Kollupitiya','CITY_LIMITS'),
    ('kotahena','Kotahena','CITY_LIMITS'),
    ('maligawatte','Maligawatte','CITY_LIMITS'),
    ('maradana','Maradana','CITY_LIMITS'),
    ('mattakkuliya','Mattakkuliya','CITY_LIMITS'),
    ('milagiriya','Milagiriya','CITY_LIMITS'),
    ('mutuwella','Mutuwella','CITY_LIMITS'),
    ('narahenpita','Narahenpita','CITY_LIMITS'),
    ('orugodawatte','Orugodawatte','CITY_LIMITS'),
    ('pettah','Pettah','CITY_LIMITS'),
    ('punchiborella','Punchi Borella','CITY_LIMITS'),
    ('slaveisland','Slave Island','CITY_LIMITS'),
    ('thimbirigasyaya','Thimbirigasyaya','CITY_LIMITS'),
    ('torrington','Torrington','CITY_LIMITS'),
    ('adikarigama','Adikarigama','FARAWAY'),
    ('agarapatana','Agarapatana','FARAWAY'),
    ('agarapatanafarm','Agarapatana Farm','FARAWAY'),
    ('agbopura','Agbopura','FARAWAY'),
    ('akiriyankumbura','Akiriyankumbura','FARAWAY'),
    ('akkara100','Akkara 100','FARAWAY'),
    ('akkarapanaha','Akkara Panaha','FARAWAY'),
    ('akkaraseeya','Akkaraseeya','FARAWAY'),
    ('akkarayankulam','Akkarayankulam','FARAWAY'),
    ('ambagaswewa','Ambagaswewa','FARAWAY'),
    ('ampagalakegalle','Ampagala -Kegalle','FARAWAY'),
    ('ampalavanpokkanai','Ampalavanpokkanai','FARAWAY'),
    ('ampilanthurai','Ampilanthurai','FARAWAY'),
    ('analaitheevu','Analai Theevu','FARAWAY'),
    ('anandapuramkilinochchi','Anandapuram Kilinochchi','FARAWAY'),
    ('aranaganvila','Aranaganvila','FARAWAY'),
    ('aranthalawa','Aranthalawa','FARAWAY'),
    ('arugambay','Arugambay','FARAWAY'),
    ('balaharuwa','Balaharuwa','FARAWAY'),
    ('balaluwewa','Balaluwewa','FARAWAY'),
    ('ballaketuwa','Ballaketuwa','FARAWAY'),
    ('bambarakele','Bambarakele','FARAWAY'),
    ('belwood','Belwood','FARAWAY'),
    ('beminiyangala','Beminiyangala','FARAWAY'),
    ('bopaththalawa','Bopaththalawa','FARAWAY'),
    ('bopitiyakegalle','Bopitiya-Kegalle','FARAWAY'),
    ('budugekanda','Budugekanda','FARAWAY'),
    ('bulupitiya','Bulupitiya','FARAWAY'),
    ('buluthota','Buluthota','FARAWAY'),
    ('bundala','Bundala','FARAWAY'),
    ('calsey','Calsey','FARAWAY'),
    ('chandanagama','Chandanagama','FARAWAY'),
    ('chenaiyoor','Chenaiyoor','FARAWAY'),
    ('dahaiyagala','Dahaiyagala','FARAWAY'),
    ('daluggolla','Daluggolla','FARAWAY'),
    ('delf','Delf','FARAWAY'),
    ('dellawa','Dellawa','FARAWAY'),
    ('deniyaya','Deniyaya','FARAWAY'),
    ('derangala','Derangala','FARAWAY'),
    ('dewalakanda','Dewalakanda','FARAWAY'),
    ('dewramvehera','Dewramvehera','FARAWAY'),
    ('dickyaya','Dickyaya','FARAWAY'),
    ('diddeniya','Diddeniya','FARAWAY'),
    ('dimbulagala','Dimbulagala','FARAWAY'),
    ('galoya','Galoya','FARAWAY'),
    ('gammaduwa','Gammaduwa','FARAWAY'),
    ('hadigallahalgollaestate','Hadigalla Halgolla Estate','FARAWAY'),
    ('halmillagolla','Halmillagolla','FARAWAY'),
    ('hatharaskotuwa','Hatharaskotuwa','FARAWAY'),
    ('higurukaduwa','Higurukaduwa','FARAWAY'),
    ('hinguralakanda','Hinguralakanda','FARAWAY'),
    ('hiniduma','Hiniduma','FARAWAY'),
    ('horowpathana','Horowpathana','FARAWAY'),
    ('hulankapoola','Hulankapoola','FARAWAY'),
    ('kahatagollewa','Kahatagollewa','FARAWAY'),
    ('kajuwatta','Kajuwatta','FARAWAY'),
    ('kakkaddicholai','Kakkaddicholai','FARAWAY'),
    ('kalaoya','Kala Oya','FARAWAY'),
    ('kalahagala','Kalahagala','FARAWAY'),
    ('kalawana','Kalawana','FARAWAY'),
    ('kalaweldeniya','Kalaweldeniya','FARAWAY'),
    ('kallarkanthale','Kallar (Kanthale)','FARAWAY'),
    ('kallarampara','Kallar(Ampara)','FARAWAY'),
    ('kalugalaududumbara','Kalugala - Ududumbara','FARAWAY'),
    ('katharagama','Katharagama','FARAWAY'),
    ('kataragama','Katharagama','FARAWAY'),
    ('kathiravely','Kathiravely','FARAWAY'),
    ('kathnoruwa','Kathnoruwa','FARAWAY'),
    ('kaudulla','Kaudulla','FARAWAY'),
    ('kayts','Kayts','FARAWAY'),
    ('kebithigollewa','Kebithigollewa','FARAWAY'),
    ('keenagahawila','Keenagahawila','FARAWAY'),
    ('keerthibandarapura','Keerthibandarapura','FARAWAY'),
    ('ketawela','Ketawela','FARAWAY'),
    ('kewestate','Kew Estate','FARAWAY'),
    ('kiliwetti','Kiliwetti','FARAWAY'),
    ('kirinda','Kirinda','FARAWAY'),
    ('kiriwaneliya','Kiriwaneliya','FARAWAY'),
    ('kiriweldola','Kiriweldola','FARAWAY'),
    ('kolamanthalawa','Kolamanthalawa','FARAWAY'),
    ('kolapathana','Kolapathana','FARAWAY'),
    ('kyts','Kyts','FARAWAY'),
    ('lagamuwa','Lagamuwa','FARAWAY'),
    ('laggala','Laggala','FARAWAY'),
    ('lahugala','Lahugala','FARAWAY'),
    ('lakshapana','Lakshapana','FARAWAY'),
    ('leula','Leula','FARAWAY'),
    ('lewaland','Lewaland','FARAWAY'),
    ('lihiniyagama','Lihiniyagama','FARAWAY'),
    ('lindawewa','Lindawewa','FARAWAY'),
    ('lipakele','Lipakele','FARAWAY'),
    ('madaganoya','Madaganoya','FARAWAY'),
    ('madolsima','Madolsima','FARAWAY'),
    ('madu','Madu','FARAWAY'),
    ('madugalla','Madugalla','FARAWAY'),
    ('madulkele','Madulkele','FARAWAY'),
    ('mahagirilla','Mahagirilla','FARAWAY'),
    ('mahanagapura','Mahanagapura','FARAWAY'),
    ('mahaoya','Mahaoya','FARAWAY'),
    ('mahasenpuratissa','Mahasenpura-Tissa','FARAWAY'),
    ('makandura','Makandura','FARAWAY'),
    ('makuldeniya','Makuldeniya','FARAWAY'),
    ('makulpotha','Makulpotha','FARAWAY'),
    ('medirigiriya','Medirigiriya','FARAWAY'),
    ('minneriya','Minneriya','FARAWAY'),
    ('minuwangete','Minuwangete','FARAWAY'),
    ('molkawa','Molkawa','FARAWAY'),
    ('mulana','Mulana','FARAWAY'),
    ('mulankavil','Mulankavil','FARAWAY'),
    ('mulativ','Mulativ','FARAWAY'),
    ('mullayaveli','Mullayaveli','FARAWAY'),
    ('mullegamaampara','Mullegama - Ampara','FARAWAY'),
    ('mulliyawalai','Mulliyawalai','FARAWAY'),
    ('neluwa','Neluwa','FARAWAY'),
    ('opatha','Opatha','FARAWAY'),
    ('padavisiripura','Padavisiripura','FARAWAY'),
    ('padaviya','Padaviya','FARAWAY'),
    ('padiyapalalla','Padiyapalalla','FARAWAY'),
    ('parayankulam','Parayankulam','FARAWAY'),
    ('pelawattekalutara','Pelawatte (Kalutara)','FARAWAY'),
    ('peraso','Peraso','FARAWAY'),
    ('periyamadu','Periyamadu','FARAWAY'),
    ('periyaneelavanai','Periyaneelavanai','FARAWAY'),
    ('pitapola','Pitapola','FARAWAY'),
    ('pointpedro','Point Pedro','FARAWAY'),
    ('pothuvil','Pothuvil','FARAWAY'),
    ('punani','Punani','FARAWAY'),
    ('puthukudeirippukili','Puthukudeirippu (Kili)','FARAWAY'),
    ('rajagalathenna','Rajagalathenna','FARAWAY'),
    ('rantabe','Rantabe','FARAWAY'),
    ('rideeella','Ridee Ella','FARAWAY'),
    ('rideebendiella','Rideebendi Ella','FARAWAY'),
    ('ridimaliyadda','Ridimaliyadda','FARAWAY'),
    ('ridiyagama','Ridiyagama','FARAWAY'),
    ('rikillagaskada','Rikillagaskada','FARAWAY'),
    ('ritigala','Ritigala','FARAWAY'),
    ('samanalatenna','Samanalatenna','FARAWAY'),
    ('samanalawattebalangoda','Samanalawatte - Balangoda','FARAWAY'),
    ('sellakataragama','Sellakataragama','FARAWAY'),
    ('sembuwatta','Sembuwatta','FARAWAY'),
    ('senapura','Senapura','FARAWAY'),
    ('sirikanduyaya','Sirikanduyaya','FARAWAY'),
    ('siripura','Siripura','FARAWAY'),
    ('sirisethagama','Sirisethagama','FARAWAY'),
    ('sithankerney','Sithankerney','FARAWAY'),
    ('sithulpahuwa','Sithul Pahuwa','FARAWAY'),
    ('siyabalagoda','Siyabalagoda','FARAWAY'),
    ('siyabalagodamatara','Siyabalagoda - Matara','FARAWAY'),
    ('skanthapuram','Skanthapuram','FARAWAY'),
    ('somapura','Somapura','FARAWAY'),
    ('somawathiya','Somawathiya','FARAWAY'),
    ('sooriyaara','Sooriya Ara','FARAWAY'),
    ('sooriyakandakahawatte','Sooriyakanda -Kahawatte','FARAWAY'),
    ('sooriyakandaemb','Sooriyakanda Emb','FARAWAY'),
    ('sripura','Sripura','FARAWAY'),
    ('srithissapura','Srithissapura','FARAWAY'),
    ('talaimannar','Talai Mannar','FARAWAY'),
    ('thanamalvila','Thanamalvila','FARAWAY'),
    ('thanthirimale','Thanthirimale','FARAWAY'),
    ('thondammanaru','Thondammanaru','FARAWAY'),
    ('thoppigala','Thoppigala','FARAWAY'),
    ('thopur','Thopur','FARAWAY'),
    ('thudawa','Thudawa','FARAWAY'),
    ('thunukkai','Thunukkai','FARAWAY'),
    ('tirukkovil','Tirukkovil','FARAWAY'),
    ('tondamannar','Tondamannar','FARAWAY'),
    ('torington','Torington','FARAWAY'),
    ('udadelwala','Uda Delwala','FARAWAY'),
    ('udamattala','Uda Mattala','FARAWAY'),
    ('uranimonaragala','Urani - Monaragala','FARAWAY'),
    ('uvathenna','Uva Thenna','FARAWAY'),
    ('uwakele','Uwakele','FARAWAY'),
    ('uyangalla','Uyangalla','FARAWAY'),
    ('vijayapurapolonnaruwa','Vijayapura - Polonnaruwa','FARAWAY'),
    ('vijithapura','Vijithapura','FARAWAY'),
    ('wadihitikanda','Wadihitikanda','FARAWAY'),
    ('wilaoya','Wilaoya','FARAWAY'),
    ('willgamuwa','Willgamuwa','FARAWAY'),
    ('willpaththu','Willpaththu','FARAWAY'),
    ('yagiralayagiraliya','Yagirala (Yagiraliya)','FARAWAY'),
    ('yakalla','Yakalla','FARAWAY'),
    ('yala','Yala','FARAWAY'),
    ('yalagamuwa','Yalagamuwa','FARAWAY'),
    ('yalkumbura','Yalkumbura','FARAWAY'),
    ('yalwela','Yalwela','FARAWAY'),
    ('yanoya','Yan Oya','FARAWAY'),
    ('yaththalgoda','Yaththalgoda','FARAWAY'),
    ('yatipawwa','Yatipawwa','FARAWAY'),
    ('yattapatha','Yattapatha','FARAWAY'),
    ('abanpola','Abanpola','OUTSTATION'),
    ('achchuveli','Achchuveli','OUTSTATION'),
    ('agalawatte','Agalawatte','OUTSTATION'),
    ('ahangama','Ahangama','OUTSTATION'),
    ('ahungalla','Ahungalla','OUTSTATION'),
    ('akmeemana','Akmeemana','OUTSTATION'),
    ('akurana','Akurana','OUTSTATION'),
    ('akurassa','Akurassa','OUTSTATION'),
    ('algama','Algama','OUTSTATION'),
    ('alma','Alma','OUTSTATION'),
    ('aluthgama','Aluthgama','OUTSTATION'),
    ('ambagastenna','Ambagastenna','OUTSTATION'),
    ('ambagasyala','Ambagasyala','OUTSTATION'),
    ('ambalakanda','Ambalakanda','OUTSTATION'),
    ('ambalangoda','Ambalangoda','OUTSTATION'),
    ('ambalantota','Ambalantota','OUTSTATION'),
    ('ambepussa','Ambepussa','OUTSTATION'),
    ('ambewela','Ambewela','OUTSTATION'),
    ('ambuluwawa','Ambuluwawa','OUTSTATION'),
    ('ampara','Ampara','OUTSTATION'),
    ('amugoda','Amugoda','OUTSTATION'),
    ('anamaduwa','Anamaduwa','OUTSTATION'),
    ('andaradeniya','Andaradeniya','OUTSTATION'),
    ('angunukolapalassa','Angunukolapalassa','OUTSTATION'),
    ('anuradhapura','Anuradhapura','OUTSTATION'),
    ('arachchikattuwa','Arachchikattuwa','OUTSTATION'),
    ('attanagalla','Attanagalla','OUTSTATION'),
    ('avissawella','Avissawella','OUTSTATION'),
    ('badalgama','Badalgama','OUTSTATION'),
    ('baddegama','Baddegama','OUTSTATION'),
    ('badulla','Badulla','OUTSTATION'),
    ('balana','Balana','OUTSTATION'),
    ('balangoda','Balangoda','OUTSTATION'),
    ('balapitiya','Balapitiya','OUTSTATION'),
    ('bambaragaswewa','Bambaragaswewa','OUTSTATION'),
    ('bandaragama','Bandaragama','OUTSTATION'),
    ('bandarawela','Bandarawela','OUTSTATION'),
    ('bangadeniya','Bangadeniya','OUTSTATION'),
    ('batticaloa','Batticaloa','OUTSTATION'),
    ('beliatta','Beliatta','OUTSTATION'),
    ('belummahra','Belummahra','OUTSTATION'),
    ('benthota','Benthota','OUTSTATION'),
    ('bentota','Benthota','OUTSTATION'),
    ('beragala','Beragala','OUTSTATION'),
    ('beruwala','Beruwala','OUTSTATION'),
    ('bibila','Bibila','OUTSTATION'),
    ('bingiriya','Bingiriya','OUTSTATION'),
    ('biyagama','Biyagama','OUTSTATION'),
    ('bogaswewa','Bogaswewa','OUTSTATION'),
    ('boooya','BooOya','OUTSTATION'),
    ('boossa','Boossa','OUTSTATION'),
    ('bulathkohupitiya','Bulathkohupitiya','OUTSTATION'),
    ('bulathsinhala','Bulathsinhala','OUTSTATION'),
    ('buttalabothale','Buttala Bothale','OUTSTATION'),
    ('chilaw','Chilaw','OUTSTATION'),
    ('dambadeniya','Dambadeniya','OUTSTATION'),
    ('dambulla','Dambulla','OUTSTATION'),
    ('dangolla','Dangolla','OUTSTATION'),
    ('dankotuwa','Dankotuwa','OUTSTATION'),
    ('dediyagala','Dediyagala','OUTSTATION'),
    ('dedugala','Dedugala','OUTSTATION'),
    ('dehiowita','Dehiowita','OUTSTATION'),
    ('delgoda','Delgoda','OUTSTATION'),
    ('delthotadedigamadankanda','Delthota Dedigama Dankanda','OUTSTATION'),
    ('demodara','Demodara','OUTSTATION'),
    ('derannawa','Derannawa','OUTSTATION'),
    ('digana','Digana','OUTSTATION'),
    ('dikwella','Dikwella','OUTSTATION'),
    ('diyavinna','Diyavinna','OUTSTATION'),
    ('dodangaslanda','Dodangaslanda','OUTSTATION'),
    ('dompe','Dompe','OUTSTATION'),
    ('dorawaka','Dorawaka','OUTSTATION'),
    ('dummalasooriya','Dummalasooriya','OUTSTATION'),
    ('eheliyagoda','Eheliyagoda','OUTSTATION'),
    ('ella','Ella','OUTSTATION'),
    ('elpitiya','Elpitiya','OUTSTATION'),
    ('embilipitiya','Embilipitiya','OUTSTATION'),
    ('enamulla','Enamulla','OUTSTATION'),
    ('eppawalla','Eppawalla','OUTSTATION'),
    ('erathna','Erathna','OUTSTATION'),
    ('galagedara','Galagedara','OUTSTATION'),
    ('galaha','Galaha','OUTSTATION'),
    ('galapitamada','Galapitamada','OUTSTATION'),
    ('galatara','Galatara','OUTSTATION'),
    ('galewela','Galewela','OUTSTATION'),
    ('galgamuwa','Galgamuwa','OUTSTATION'),
    ('galle','Galle','OUTSTATION'),
    ('gampola','Gampola','OUTSTATION'),
    ('ganemulla','Ganemulla','OUTSTATION'),
    ('ganewalpola','Ganewalpola','OUTSTATION'),
    ('gelioya','Gelioya','OUTSTATION'),
    ('ginigathhena','Ginigathhena','OUTSTATION'),
    ('ginthota','Ginthota','OUTSTATION'),
    ('giriulla','Giriulla','OUTSTATION'),
    ('gonawila','Gonawila','OUTSTATION'),
    ('goodwood','Goodwood','OUTSTATION'),
    ('habaraduwa','Habaraduwa','OUTSTATION'),
    ('habarana','Habarana','OUTSTATION'),
    ('hagala','Hagala','OUTSTATION'),
    ('hakmana','Hakmana','OUTSTATION'),
    ('haliella','Haliella','OUTSTATION'),
    ('hambantota','Hambantota','OUTSTATION'),
    ('handessa','Handessa','OUTSTATION'),
    ('hanwella','Hanwella','OUTSTATION'),
    ('haputhale','Haputhale','OUTSTATION'),
    ('hatton','Hatton','OUTSTATION'),
    ('hikkaduwa','Hikkaduwa','OUTSTATION'),
    ('horana','Horana','OUTSTATION'),
    ('horape','Horape','OUTSTATION'),
    ('hunukete','Hunukete','OUTSTATION'),
    ('ibbagamuwa','ibbagamuwa','OUTSTATION'),
    ('ittepana','Ittepana','OUTSTATION'),
    ('jaela','Ja-Ela','OUTSTATION'),
    ('jaffna','jaffna','OUTSTATION'),
    ('kadugannawa','Kadugannawa','OUTSTATION'),
    ('kahathuduwa','Kahathuduwa','OUTSTATION'),
    ('kahawatte','Kahawatte','OUTSTATION'),
    ('kallar','Kallar','OUTSTATION'),
    ('kalupahana','Kalupahana','OUTSTATION'),
    ('kaluthara','Kaluthara','OUTSTATION'),
    ('kandana','Kandana','OUTSTATION'),
    ('kandiyapita','Kandiyapita','OUTSTATION'),
    ('kandy','Kandy','OUTSTATION'),
    ('karaitivu','Karaitivu','OUTSTATION'),
    ('karaveddi','Karaveddi','OUTSTATION'),
    ('katana','Katana','OUTSTATION'),
    ('katugastota','Katugastota','OUTSTATION'),
    ('katunayake','Katunayake','OUTSTATION'),
    ('katuwana','Katuwana','OUTSTATION'),
    ('kegalle','Kegalle','OUTSTATION'),
    ('kekirawa','Kekirawa','OUTSTATION'),
    ('kellapatha','Kellapatha','OUTSTATION'),
    ('kepumgoda','Kepumgoda','OUTSTATION'),
    ('ketandola','Ketandola','OUTSTATION'),
    ('kilinochchi','Kilinochchi','OUTSTATION'),
    ('kiriella','Kiriella','OUTSTATION'),
    ('kirillawala','Kirillawala','OUTSTATION'),
    ('kirindiwela','Kirindiwela','OUTSTATION'),
    ('kitulgala','Kitulgala','OUTSTATION'),
    ('kobeigane','Kobeigane','OUTSTATION'),
    ('koggala','Koggala','OUTSTATION'),
    ('koongahawela','Koongahawela','OUTSTATION'),
    ('kotmale','Kotmale','OUTSTATION'),
    ('kuliyapitiya','Kuliyapitiya','OUTSTATION'),
    ('kundasale','Kundasale','OUTSTATION'),
    ('kurunegala','Kurunegala','OUTSTATION'),
    ('kuruwita','Kuruwita','OUTSTATION'),
    ('lenamamatugama','Lenama Matugama','OUTSTATION'),
    ('madiwakamadampe','Madiwaka Madampe','OUTSTATION'),
    ('mahawa','Mahawa','OUTSTATION'),
    ('mahawewa','Mahawewa','OUTSTATION'),
    ('maskeliya','Maskeliya','OUTSTATION'),
    ('matale','Matale','OUTSTATION'),
    ('matara','Matara','OUTSTATION'),
    ('meegoda','Meegoda','OUTSTATION'),
    ('minuwangoda','Minuwangoda','OUTSTATION'),
    ('mirigama','Mirigama','OUTSTATION'),
    ('miriswatte','Miriswatte','OUTSTATION'),
    ('monaragala','Monaragala','OUTSTATION'),
    ('morawaka','Morawaka','OUTSTATION'),
    ('nainamadama','Nainamadama','OUTSTATION'),
    ('nalanda','Nalanda','OUTSTATION'),
    ('nalluruwa','Nalluruwa','OUTSTATION'),
    ('narammala','Narammala','OUTSTATION'),
    ('naththandiya','Naththandiya','OUTSTATION'),
    ('naula','Naula','OUTSTATION'),
    ('navatkuli','Navatkuli','OUTSTATION'),
    ('negombo','Negombo','OUTSTATION'),
    ('nelliady','Nelliady','OUTSTATION'),
    ('neluyaya','Neluyaya','OUTSTATION'),
    ('nikaweratiya','Nikaweratiya','OUTSTATION'),
    ('nindur','Nindur','OUTSTATION'),
    ('nittabuwa','Nittabuwa','OUTSTATION'),
    ('niwithigala','Niwithigala','OUTSTATION'),
    ('niyagama','Niyagama','OUTSTATION'),
    ('nochchiyagama','Nochchiyagama','OUTSTATION'),
    ('norochchole','Norochchole','OUTSTATION'),
    ('nuwaraeliya','NuwaraEliya','OUTSTATION'),
    ('padalangala','Padalangala','OUTSTATION'),
    ('padeniya','Padeniya','OUTSTATION'),
    ('padukka','Padukka','OUTSTATION'),
    ('palagala','Palagala','OUTSTATION'),
    ('palavi','Palavi','OUTSTATION'),
    ('pallebedda','Pallebedda','OUTSTATION'),
    ('pallegama','Pallegama','OUTSTATION'),
    ('pannala','Pannala','OUTSTATION'),
    ('pasikuda','Pasikuda','OUTSTATION'),
    ('passara','Passara','OUTSTATION'),
    ('pelampitiyapadiyathalawa','Pelampitiya Padiyathalawa','OUTSTATION'),
    ('pelmadulla','Pelmadulla','OUTSTATION'),
    ('peradeniya','Peradeniya','OUTSTATION'),
    ('pinnawala','Pinnawala','OUTSTATION'),
    ('pitigala','Pitigala','OUTSTATION'),
    ('pokunuwita','Pokunuwita','OUTSTATION'),
    ('polgahawela','Polgahawela','OUTSTATION'),
    ('polonnaruwa','Polonnaruwa','OUTSTATION'),
    ('pothuhera','Pothuhera','OUTSTATION'),
    ('pugoda','Pugoda','OUTSTATION'),
    ('pussellawa','Pussellawa','OUTSTATION'),
    ('puttlam','Puttlam','OUTSTATION'),
    ('ragama','Ragama','OUTSTATION'),
    ('rajanganaya','Rajanganaya','OUTSTATION'),
    ('rakwana','Rakwana','OUTSTATION'),
    ('ramboda','Ramboda','OUTSTATION'),
    ('rambukkana','Rambukkana','OUTSTATION'),
    ('ranajayapura','Ranajayapura','OUTSTATION'),
    ('ranna','Ranna','OUTSTATION'),
    ('rathnapura','Rathnapura','OUTSTATION'),
    ('ratnapura','Ratnapura','OUTSTATION'),
    ('ruwanwella','Ruwanwella','OUTSTATION'),
    ('sangarajapura','Sangarajapura','OUTSTATION'),
    ('seeduwa','Seeduwa','OUTSTATION'),
    ('tabuththegama','Tabuththegama','OUTSTATION'),
    ('talawa','Talawa','OUTSTATION'),
    ('tewatta','Tewatta','OUTSTATION'),
    ('thalawakele','Thalawakele','OUTSTATION'),
    ('thangalle','Thangalle','OUTSTATION'),
    ('trincomalee','Trincomalee','OUTSTATION'),
    ('vavuniyavitharandeniya','Vavuniya Vitharandeniya','OUTSTATION'),
    ('wadduwa','Wadduwa','OUTSTATION'),
    ('warakapola','Warakapola','OUTSTATION'),
    ('wariyapola','Wariyapola','OUTSTATION'),
    ('wattegamaweligama','Wattegama Weligama','OUTSTATION'),
    ('welimada','Welimada','OUTSTATION'),
    ('wennapuwa','Wennapuwa','OUTSTATION'),
    ('weyangoda','Weyangoda','OUTSTATION'),
    ('yakkala','Yakkala','OUTSTATION'),
    ('yatiyanthota','Yatiyanthota','OUTSTATION'),
    ('angoda','Angoda','SUBURBS'),
    ('angulana','Angulana','SUBURBS'),
    ('athurugiriya','Athurugiriya','SUBURBS'),
    ('attidiya','Attidiya','SUBURBS'),
    ('batakettara','Batakettara','SUBURBS'),
    ('battaramulla','Battaramulla','SUBURBS'),
    ('beddagana','Beddagana','SUBURBS'),
    ('bellanwila','Bellanwila','SUBURBS'),
    ('bokundara','Bokundara','SUBURBS'),
    ('boralesgamuwa','Boralesgamuwa','SUBURBS'),
    ('borupana','Borupana','SUBURBS'),
    ('dehiwala','Dehiwala','SUBURBS'),
    ('dehiwalamountlavinia','Dehiwala','SUBURBS'),
    ('egodauyana','EgodaUyana','SUBURBS'),
    ('homagama','Homagama','SUBURBS'),
    ('hunupitiya','Hunupitiya','SUBURBS'),
    ('kadawatha','Kadawatha','SUBURBS'),
    ('kalubowila','Kalubowila','SUBURBS'),
    ('katubedda','Katubedda','SUBURBS'),
    ('kelaniya','Kelaniya','SUBURBS'),
    ('kesbewa','Kesbewa','SUBURBS'),
    ('kiribathgoda','Kiribathgoda','SUBURBS'),
    ('kohuwala','Kohuwala','SUBURBS'),
    ('kolonnawa','Kolonnawa','SUBURBS'),
    ('kottawa','Kottawa','SUBURBS'),
    ('kotte','Kotte','SUBURBS'),
    ('srijayawardenepurakotte','Kotte','SUBURBS'),
    ('maharagama','Maharagama','SUBURBS'),
    ('makola','Makola','SUBURBS'),
    ('malabe','Malabe','SUBURBS'),
    ('moratuwa','Moratuwa','SUBURBS'),
    ('mtlavinia','Mt. Lavinia','SUBURBS'),
    ('mountlavinia','Mt. Lavinia','SUBURBS'),
    ('nawala','Nawala','SUBURBS'),
    ('nugegoda','Nugegoda','SUBURBS'),
    ('pannipitiya','Pannipitiya','SUBURBS'),
    ('peliyagoda','Peliyagoda','SUBURBS'),
    ('pepiliyana','Pepiliyana','SUBURBS'),
    ('piliyandala','Piliyandala','SUBURBS'),
    ('ratmalana','Ratmalana','SUBURBS'),
    ('rukmalgama','Rukmalgama','SUBURBS'),
    ('sapugaskanda','Sapugaskanda','SUBURBS'),
    ('wattala','Wattala','SUBURBS'),
    ('wellampitiya','Wellampitiya','SUBURBS');

-- Postal-code fallbacks (when city not matched)
UPDATE postal_zone SET courier_zone = 'CITY_LIMITS'
  WHERE postal_code >= '00100' AND postal_code <= '01500';

UPDATE postal_zone SET courier_zone = 'SUBURBS'
  WHERE district IN ('Colombo','Gampaha','Kalutara')
    AND NOT (postal_code >= '00100' AND postal_code <= '01500');

UPDATE postal_zone SET courier_zone = 'FARAWAY'
  WHERE district IN ('Mannar','Mullaitivu');

UPDATE postal_zone SET courier_zone = 'OUTSTATION'
  WHERE district NOT IN ('Colombo','Gampaha','Kalutara','Mannar','Mullaitivu');

