-- In-app customer notification inbox (header bell).
CREATE TABLE customer_inbox (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    type         VARCHAR(32)  NOT NULL,
    title        VARCHAR(200) NOT NULL,
    body         VARCHAR(500),
    link         VARCHAR(500),
    source_key   VARCHAR(120),
    read_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT customer_inbox_type_check CHECK (type IN (
        'ORDER_MESSAGE', 'QUOTE_REPLY', 'STOCK_RESTOCK', 'NEW_PRODUCT'
    ))
);

CREATE UNIQUE INDEX ux_customer_inbox_source
    ON customer_inbox(customer_id, source_key)
    WHERE source_key IS NOT NULL;

CREATE INDEX ix_customer_inbox_feed
    ON customer_inbox(customer_id, created_at DESC);
