-- V47 — Catalog sync to the owner's corrected 2026-07-16 product sheet (generated by
-- backend/scripts/generate_catalog_csv_sync.py — see that header for scope).
-- Existing products are updated by slug; description keeps admin-typed text (COALESCE);
-- value fixes are guarded by the current seeded value so admin edits survive re-runs.

-- V40 re-fix, keyed by slug: V40 moved the A4-size canvas board to 'Canvas' guarded by a
-- hardcoded product id (383), which is a no-op on any freshly-seeded database where ids
-- differ. Same correction, robust key (runs before the category_group updates below).
UPDATE product SET category = 'Canvas'
WHERE slug = 'scan-canvas-board-a4-size-canvas-board' AND category = 'A4 Size Writing Board';

-- PDF letters G and H are separate categories; V36's category map filed the with-stand
-- glass board under G ('glass board' matched before 'glass board with stand').
UPDATE product SET category = 'Glass Writing Board with Stand'
WHERE slug = 'glass-board-with-stand' AND category = 'Glass Writing Board';

-- Top-level storefront groups (the sheet's eight numbered headers, V46 category_group).
UPDATE product SET category_group = 'Kids Corner' WHERE category = 'A4 Size Writing Board';
UPDATE product SET category_group = 'Art Supplies' WHERE category = 'Architectural Drawing Board';
UPDATE product SET category_group = 'Writing Boards' WHERE category = 'Black Board';
UPDATE product SET category_group = 'Art Supplies' WHERE category = 'Canvas';
UPDATE product SET category_group = 'Sport / Game Boards' WHERE category = 'Carrom Board';
UPDATE product SET category_group = 'Sport / Game Boards' WHERE category = 'Dam / Chess Board';
UPDATE product SET category_group = 'Writing Boards' WHERE category = 'Eco Board';
UPDATE product SET category_group = 'Writing Boards' WHERE category = 'Five Rule';
UPDATE product SET category_group = 'Writing Boards' WHERE category = 'Flip Chart and Paper Set';
UPDATE product SET category_group = 'Writing Boards' WHERE category = 'Glass Writing Board';
UPDATE product SET category_group = 'Writing Boards' WHERE category = 'Glass Writing Board with Stand';
UPDATE product SET category_group = 'Writing Boards' WHERE category = 'Green Board';
UPDATE product SET category_group = 'Key Holder' WHERE category = 'Key Holder';
UPDATE product SET category_group = 'Kids Corner' WHERE category = 'Kids Board';
UPDATE product SET category_group = 'Menu Board And Other Restaurant Items' WHERE category = 'Menu Board';
UPDATE product SET category_group = 'Portable Partition' WHERE category = 'Mobile Partition';
UPDATE product SET category_group = 'Pin Up Board / Notice Board' WHERE category = 'Pin Board / Notice Board';
UPDATE product SET category_group = 'Writing Boards' WHERE category = 'White Board';
UPDATE product SET category_group = 'Art Supplies' WHERE category = 'Wooden Easel';

-- Storefront order + sheet descriptions, per product (sheet row order = display order).
-- note: row 378: duplicate 'Baby Carrom Board' (cross-listed) — first occurrence wins
UPDATE product SET display_order = 2,
    description = COALESCE(NULLIF(description, ''), 'White Writing Smooth Dry Erase Surface,High Quality Aluminium Frame,Plastic Corners,Ready to Hang With Alumium Hooks,To be used with white board marker,Made in Sri Lanka')
WHERE slug = 'scan-white-board';
UPDATE product SET display_order = 25,
    description = COALESCE(NULLIF(description, ''), 'High quality glossy white, 100% dry erase surface ,Can stick magnetic dusters, buttons & magnetic markers to board, To be used with white board marker, Plastic corners for added safety, Board is Ready to hang steadily with strong aluminium hooks , Made in Sri Lanka')
WHERE slug = 'scan-magnetic-white-board';
UPDATE product SET display_order = 38,
    description = COALESCE(NULLIF(description, ''), 'Exclusively manufactured by us in Sri Lanka. Import from Belgium , 25 years of Warranty, Custom sizes ( Any length without joints ), Zero glare ,Full magnetic, Built to last, Can use for Projector Interface As Well. Durable & professional look .')
WHERE slug = 'ceramic-steel-magnetic-white-board';
UPDATE product SET display_order = 47,
    description = COALESCE(NULLIF(description, ''), 'Stand :- Stand Made From Hammer Painted Galvanized Steel. With Caster Wheels You Can Move The Stand. And Board Can Be Rotate.Height Can Be Adjust. White Board :- White Writing Smooth Dry Erase Surface, High Quality Aluminium / PVC Frame, Plastic Corners, Ready To Hang With Alumium Hooks, To be used with white board marker,Made in Sri Lanka')
WHERE slug = 'scan-white-board-with-stand';
UPDATE product SET display_order = 59,
    description = COALESCE(NULLIF(description, ''), 'Stand :- Stand Made From Hammer Painted Galvanized Steel. With Caster Wheels You Can Move The Stand. And Board Can Be Rotate.Height Can Be Adjust. Magnetic White Board :-High quality glossy white, 100% dry erase surface ,Can stick magnetic dusters, buttons & magnetic markers to board, To be used with white board marker, Plastic corners for added safety, Board is Ready to hang steadily with strong aluminium hooks , Made in Sri Lanka')
WHERE slug = 'scan-magnetic-white-board-with-stand';
UPDATE product SET display_order = 71,
    description = COALESCE(NULLIF(description, ''), 'Stand - Stand Made From Hammer Painted Galvanized Steel. With Caster Wheels You Can Move The Stand. And Board Can Be Rotate.Height Can Be Adjust.')
WHERE slug = 'white-board-stand-only';
UPDATE product SET display_order = 77,
    description = COALESCE(NULLIF(description, ''), 'Green Chalk Board Made Out Of Melamine Green And White Board As Double Sided Board, Strong Aluminium frame with Aluminum Hooks To Hang, Non Magnetic')
WHERE slug = 'scan-green-board-alumium-frame';
UPDATE product SET display_order = 95,
    description = COALESCE(NULLIF(description, ''), 'Green Board :- Green Chalk Board Made Out Of Melamine Green And White Board As Double Sided Board, Strong Aluminium frame with Aluminum Hooks To Hang, Non Magnetic. Stand :- Stand - Stand Made From Hammer Painted Galvanized Steel. With Caster Wheels You Can Move The Stand. And Board Can Be Rotate.Height Can Be Adjust.')
WHERE slug = 'scan-green-board-with-stand';
UPDATE product SET display_order = 107,
    description = COALESCE(NULLIF(description, ''), 'Green Chalk board Made Out Of Melamine Green Board With Pine Wood Frame. Less Glare When Teaching Online, Easy To Hang With Hooks Attached')
WHERE slug = 'scan-green-board-wooden-frame';
UPDATE product SET display_order = 116,
    description = COALESCE(NULLIF(description, ''), 'Original Matt Surface Green Chalk Board Can Be Use With Chalk, Non Slippery, Durable, High Visiblity, Dust Free, Made In Sri Lanka')
WHERE slug = 'scan-green-magnetic-board';
UPDATE product SET display_order = 129,
    description = COALESCE(NULLIF(description, ''), 'Original Green Magnetic Board :- Original Matt Surface Green Chalk Board Can Be Use With Chalk, Non Slippery, Durable, High Visiblity, Dust Free, Made In Sri Lanka Stand :- Stand Made From Hammer Painted Galvanized Steel. With Caster Wheels You Can Move The Stand. And Board Can Be Rotate.Height Can Be Adjust')
WHERE slug = 'scan-green-magnetic-board-with-stand';
UPDATE product SET display_order = 141,
    description = COALESCE(NULLIF(description, ''), 'Original Black Chalk MDF Board. Can Be Use With Chalk, Non Slippery, Durable, Higher Visiblity, Strong Aluminium Frame With Aluminum Hooks To Hang. Made In Sri Lanka, Trsuted Brand Scan')
WHERE slug = 'scan-black-board-alumium-frame';
UPDATE product SET display_order = 155,
    description = COALESCE(NULLIF(description, ''), 'Original Black Chalk MDF Board. Can Be Use With Chalk, Non Slippery, Durable, Higher Visiblity, Strong Aluminium Frame With Aluminum Hooks To Hang. Made In Sri Lanka, Trsuted Brand Scan')
WHERE slug = 'scan-black-board-wooden-frame';
UPDATE product SET display_order = 164,
    description = COALESCE(NULLIF(description, ''), 'It''s Original White Board With Screen Printed Five Rules. High Quality Aluminium Frame,Plastic Corners,Ready to Hang With Alumium Hooks,To be used with white board marker,Made in Sri Lanka')
WHERE slug = 'five-rule-white-board';
UPDATE product SET display_order = 166,
    description = COALESCE(NULLIF(description, ''), 'It''s Original Green Board With Screen Printed Five Rules. High Quality Aluminium Frame,Plastic Corners,Ready to Hang With Alumium Hooks,To be used with Chalk,Made in Sri Lanka')
WHERE slug = 'five-rule-green-board';
UPDATE product SET display_order = 168,
    description = COALESCE(NULLIF(description, ''), 'It''s Original Black Board With Screen Printed Five Rules. High Quality Aluminium Frame,Plastic Corners,Ready to Hang With Alumium Hooks,To be used with Chalk,Made in Sri Lanka')
WHERE slug = 'five-rule-black-board';
UPDATE product SET display_order = 171,
    description = COALESCE(NULLIF(description, ''), 'High Quality White / Green / Black Writing Board With Fine Pine Wood Frame. Child Friendly')
WHERE slug = 'wooden-frame-eco-board';
UPDATE product SET display_order = 177,
    description = COALESCE(NULLIF(description, ''), 'It is a tempered glass with 6mm thickness and it''s 5X Strenghten. It''s Flat Edge And Round Corners. Fix With Stainless Steel Studs. Free Back Coating. Also, we have the technology to install our Glass Board even on Partition Boards and Gypsum Boards. You Can Write On It Using White Board Marker')
WHERE slug = 'glass-board';
UPDATE product SET display_order = 184,
    description = COALESCE(NULLIF(description, ''), 'It is a tempered glass with 6mm thickness and it''s 5X Strenghten. It''s Flat Edge And Round Corners. Fix With Stainless Steel Studs. Free Back Coating. Also, we have the technology to install our Glass Board even on Partition Boards and Gypsum Boards. You Can Write On It Using White Board Marker. Stand Comes with Heavy Steel Stand')
WHERE slug = 'glass-board-with-stand';
UPDATE product SET display_order = 189,
    description = COALESCE(NULLIF(description, ''), 'TRIPOD: You Can Adjust The Height Through Telescoping Knob. Stand is Hammer Finished. Foldable And Lightweight Design For Easy Installation And Carrying. FLIP CHART BOARD: The tripod whiteboard ( 3 X 2 FT ) Comes With A Steel Elastic Clamp And Two Flip Chart Hooks On The Top For Hanging Pads, Flipcharts, Papers, Files, Posters, Calendars Or Other Presentation Materials.')
WHERE slug = 'tripod-flip-chart';
UPDATE product SET display_order = 190,
    description = COALESCE(NULLIF(description, ''), 'You Can Adjust The Height Through Telescoping Knob. Stand is PoCan Move. Steady And Strong Paper Locking Mechanism. Smooth And Durable High Quality Writing Surface Of 2 x 3 FT White Board.wder Coated. Flipchart Consisting Of Circular Base With Caster Wheels And')
WHERE slug = 'flip-chart-with-caster-wheels';
UPDATE product SET display_order = 191,
    description = COALESCE(NULLIF(description, ''), 'Thickness : 60gsm, Size : 34 x 24 inch')
WHERE slug = 'flip-chart-paper-set';
UPDATE product SET display_order = 195,
    description = COALESCE(NULLIF(description, ''), 'High Quality Colorful Velvet Surface Pin Board, Made With Rubber Sheet In Underneath, Strong Aluminium Frame and Ready To Hang With Metal Hooks, To be used as Notice Board. Made in Sri Lanka')
WHERE slug = 'pin-board';
UPDATE product SET display_order = 212,
    description = COALESCE(NULLIF(description, ''), 'Top Quality Cork Sheets Used For Easy Penetration And Strong Hold For The Pins, Strong Aluminium Frame and Ready To Hang With Metal Hooks for easy hanging, Wide range of sizes to choose from, Made in Sri Lanka')
WHERE slug = 'cork-board-aluminum-frame';
UPDATE product SET display_order = 222,
    description = COALESCE(NULLIF(description, ''), 'Top Quality Cork Sheets Used For Easy Penetration And Strong Hold For The Pins, Strong Eco Friendly Pine Wood Frame and Ready To Hang With Metal Hooks for easy hanging, Wide range of sizes to choose from, Made in Sri Lanka')
WHERE slug = 'cork-board-wooden-frame';
UPDATE product SET display_order = 233,
    description = COALESCE(NULLIF(description, ''), 'Top Quality Cork Sheets Used For Easy Penetration And Strong Hold For The Pins, And Also The White Board Provides You The Extra Benifits To Note Down Some Special Things. Strong Aluminum Frame and Ready To Hang With Metal Hooks For Easy Hanging, Wide Range Of Sizes To Choose From, Made In Sri Lanka')
WHERE slug = 'combination-board-aluminium-frame';
UPDATE product SET display_order = 234,
    description = COALESCE(NULLIF(description, ''), 'Top Quality Cork Sheets Used For Easy Penetration And Strong Hold For The Pins, And Also The White Board Provides You The Extra Benifits To Note Down Some Special Things. Strong Eco Friendly Pine Wood Frame and Ready To Hang With Metal Hooks For Easy Hanging, Wide Range Of Sizes To Choose From, Made In Sri Lanka')
WHERE slug = 'combination-board-wooden-frame';
UPDATE product SET display_order = 236,
    description = COALESCE(NULLIF(description, ''), 'High Quality Colorful Velvet Surface Pin Board, Made With Rubber Sheet In Underneath, High Quality Aluminium Box Bar Frame With Lockable Sliding Glass Door. To be used as Notice Board, Improved Modern Design.')
WHERE slug = 'sliding-glass-notice-board';
UPDATE product SET display_order = 245,
    description = COALESCE(NULLIF(description, ''), 'High Quality Colorful Velvet Surface Pin Board, Made With Rubber Sheet In Underneath, High Quality Aluminium Box Bar Frame With Lockable Front Glass Door. To be used as Notice Board, Improved Modern Design.')
WHERE slug = 'front-door-glass-notice-board';
UPDATE product SET display_order = 250,
    description = COALESCE(NULLIF(description, ''), 'High Quality Colorful Velvet Surface Pin Board, Made With Rubber Sheet In Underneath, High Quality Aluminium Box Bar Frame With Lockable Glass Door. To be used as Notice Board, Improved Modern Design.')
WHERE slug = 'shock-door-glass-notice-board';
UPDATE product SET display_order = 255
WHERE slug = 'moderation-zopp-board';
UPDATE product SET display_order = 258,
    description = COALESCE(NULLIF(description, ''), 'Premium-grade Canvas Boards suitable for artists, institutions, and studios. 280GSM, 100% Cotton Material With Acrylic Titanium Primed.Custom Sizes Are Available')
WHERE slug = 'scan-canvas-board';
UPDATE product SET display_order = 261,
    description = COALESCE(NULLIF(description, ''), 'Premium-grade Canvas Boards suitable for artists, institutions, and studios. 280GSM, 100% Cotton Material With Acrylic Titanium Primed.Custom Sizes Are Available')
WHERE slug = 'scan-canvas-board-a4-size-canvas-board';
UPDATE product SET display_order = 262,
    description = COALESCE(NULLIF(description, ''), 'Premium-grade Canvas Boards suitable for artists, institutions, and studios. 280GSM, 100% Cotton Material With Acrylic Titanium Primed.Custom Sizes Are Available')
WHERE slug = 'scan-canvas-board-2';
UPDATE product SET display_order = 268,
    description = COALESCE(NULLIF(description, ''), 'Premium-grade Canvas Boards suitable for artists, institutions, and studios. 280GSM, 100% Cotton Material With Acrylic Titanium Primed.Custom Sizes Are Available')
WHERE slug = 'scan-canvas-board-a3-size-canvas-board';
UPDATE product SET display_order = 269,
    description = COALESCE(NULLIF(description, ''), 'Premium-grade Canvas Boards suitable for artists, institutions, and studios. 280GSM, 100% Cotton Material With Acrylic Titanium Primed.Custom Sizes Are Available')
WHERE slug = 'scan-canvas-board-3';
UPDATE product SET display_order = 275,
    description = COALESCE(NULLIF(description, ''), 'Premium-grade Canvas Boards suitable for artists, institutions, and studios. 280GSM, 100% Cotton Material With Acrylic Titanium Primed.Custom Sizes Are Available')
WHERE slug = 'scan-canvas-board-a2-size-canvas-board';
UPDATE product SET display_order = 276,
    description = COALESCE(NULLIF(description, ''), 'Premium-grade Canvas Boards suitable for artists, institutions, and studios. 280GSM, 100% Cotton Material With Acrylic Titanium Primed.Custom Sizes Are Available')
WHERE slug = 'scan-canvas-board-4';
UPDATE product SET display_order = 282,
    description = COALESCE(NULLIF(description, ''), 'Made Out Of High-Quality Pine Wood, Eco friendly & Easy To Assemble With Instruction Notes Provided. Height is 3.5ftft And It''s Adjustable. Made in Sri Lanka by Scan Lanka')
WHERE slug = 'kids-easel';
UPDATE product SET display_order = 283,
    description = COALESCE(NULLIF(description, ''), 'Made Out Of High-Quality Pine Wood, Eco friendly & Easy To Assemble With Instruction Notes Provided. Height is 2ft. Made in Sri Lanka by Scan Lanka')
WHERE slug = 'medium-easel';
UPDATE product SET display_order = 284,
    description = COALESCE(NULLIF(description, ''), 'Made Out Of High-Quality Pine Wood, Eco friendly & Easy To Assemble With Instruction Notes Provided. Height is 5ft And It''s Adjustable. Made in Sri Lanka by Scan Lanka')
WHERE slug = 'large-easel';
UPDATE product SET display_order = 285,
    description = COALESCE(NULLIF(description, ''), 'Made Out Of High-Quality Pine Wood, Eco friendly. Height is 7inch. Made in Sri Lanka by Scan Lanka')
WHERE slug = 'mini-easel';
UPDATE product SET display_order = 286,
    description = COALESCE(NULLIF(description, ''), '2 X 2 1/2 FT Art Board Comes With Two Steel Art Board Hooks And 5FT Height Adjustable Large Easel. Can Hang Canvases, Papers, Posters')
WHERE slug = 'wooden-easel-art-board';
UPDATE product SET display_order = 296,
    description = COALESCE(NULLIF(description, ''), 'Scan Pine /Teak Wood Single Side Menu Board, High Quality Imported Black Board Surface, Attractive Design To Be Written With Chalk, Eco Friendly. Made in Sri Lanka')
WHERE slug = 'single-side-menu-board';
UPDATE product SET display_order = 298,
    description = COALESCE(NULLIF(description, ''), 'Scan Pine /Teak Wood Single Side Menu Board, High Quality Imported Black Board Surface, Attractive Design To Be Written With Chalk, Eco Friendly. Made in Sri Lanka')
WHERE slug = 'single-side-teak-menu-board';
UPDATE product SET display_order = 299,
    description = COALESCE(NULLIF(description, ''), 'Scan Pine /Teak Wood Single Side Menu Board, High Quality Imported Black Board Surface, Attractive Design To Be Written With Chalk, Eco Friendly. Made in Sri Lanka')
WHERE slug = 'single-side-menu-board-2';
UPDATE product SET display_order = 302,
    description = COALESCE(NULLIF(description, ''), 'High Quality Imported Black Board Surface Attractive Design With Two Boards To Be Written By Chalk & Seen By Both Sides, Pine Wood Used For Frame Enables Better Product Life,Eco Friendly. Made in Sri Lanka')
WHERE slug = 'dual-menu-board';
UPDATE product SET display_order = 304,
    description = COALESCE(NULLIF(description, ''), 'High Quality Imported Black Board Surface Attractive Design With Two Boards To Be Written By Chalk & Seen By Both Sides, Pine Wood Used For Frame Enables Better Product Life,Eco Friendly. Made in Sri Lanka')
WHERE slug = 'dual-teak-menu-board';
UPDATE product SET display_order = 305,
    description = COALESCE(NULLIF(description, ''), 'High Quality Imported Black Board Surface Attractive Design With Two Boards To Be Written By Chalk & Seen By Both Sides, Pine Wood Used For Frame Enables Better Product Life,Eco Friendly. Made in Sri Lanka')
WHERE slug = 'dual-menu-board-2';
UPDATE product SET display_order = 308
WHERE slug = 'double-side-menu-board';
UPDATE product SET display_order = 311,
    description = COALESCE(NULLIF(description, ''), 'Made from pine wood, Erasble black board surface, Made in Sri Lanka by Scan Lanka your trusted educational equipment manufacturer.')
WHERE slug = 'buffet-tag-table-top';
UPDATE product SET display_order = 312,
    description = COALESCE(NULLIF(description, ''), 'Made from pine wood, Erasble black board surface, Made in Sri Lanka by Scan Lanka your trusted educational equipment manufacturer.')
WHERE slug = 'table-top';
UPDATE product SET display_order = 314,
    description = COALESCE(NULLIF(description, ''), 'Made from pine wood, Erasble black board surface, Made in Sri Lanka by Scan Lanka your trusted educational equipment manufacturer.')
WHERE slug = 'price-tag-with-stick';
UPDATE product SET display_order = 316,
    description = COALESCE(NULLIF(description, ''), 'Acrylic name boards comes with Premium quality clear acrylic material, Single Side & Double Side options available, Custom names/ food names/titles/ logos and room numbers can display through this. Multiple sizes available. Durable, lightweight, and easy to clean')
WHERE slug = 'acrylic-name-board-single-side';
UPDATE product SET display_order = 323,
    description = COALESCE(NULLIF(description, ''), 'Acrylic name boards comes with Premium quality clear acrylic material, Single Side & Double Side options available, Custom names/ food names/titles/ logos and room numbers can display through this. Multiple sizes available. Durable, lightweight, and easy to clean')
WHERE slug = 'acrylic-name-board-double-side';
UPDATE product SET display_order = 338,
    description = COALESCE(NULLIF(description, ''), 'Includes 24 carrom coins, Material: Plastic, Color: Multi')
WHERE slug = 'sport-items-scan-carrom-men-set-with-disk';
UPDATE product SET display_order = 340,
    description = COALESCE(NULLIF(description, ''), 'Nylone disk')
WHERE slug = 'sport-items-wining-disk';
UPDATE product SET display_order = 341,
    description = COALESCE(NULLIF(description, ''), 'Plastic Men Set')
WHERE slug = 'sport-items-dam-men-set';
UPDATE product SET display_order = 342
WHERE slug = 'sport-items-boric-small-15g';
UPDATE product SET display_order = 343
WHERE slug = 'sport-items-boric-large-60g';
UPDATE product SET display_order = 345,
    description = COALESCE(NULLIF(description, ''), 'Made Out Of Treated Rubber Wood Frame And The Surface Made By Chinese Plywood.With High Quality Free Ment Set.')
WHERE slug = 'dam-board';
UPDATE product SET display_order = 346,
    description = COALESCE(NULLIF(description, ''), 'Made Out Of Treated Rubber Wood Frame And The Surface Made By Chinese Plywood.With High Quality Free Ment Set.')
WHERE slug = 'dam-board-teak-wood';
UPDATE product SET display_order = 347,
    description = COALESCE(NULLIF(description, ''), 'Made Out Of Treated Rubber Wood Frame And The Surface Made By Chinese Plywood.With High Quality Free Ment Set.')
WHERE slug = 'chess-board';
UPDATE product SET display_order = 348,
    description = COALESCE(NULLIF(description, ''), 'Made Out Of Treated Rubber Wood Frame And The Surface Made By Chinese Plywood.With High Quality Free Ment Set.')
WHERE slug = 'chess-board-teak-wood';
UPDATE product SET display_order = 350,
    description = COALESCE(NULLIF(description, ''), 'SIZE : 29" X 29" PLAY AREA / OUT SIDE -34'''',THICKNESS : 3MMSURFACE : CHINESE PLYWOOD, FRAME : TREATED MAHOGANI , FRAME SIZE : 3"X 1",WEIGHT : 5.3KG,FREE COINS SET | STRIKER')
WHERE slug = 'practice-carrom-board';
UPDATE product SET display_order = 351,
    description = COALESCE(NULLIF(description, ''), 'SIZE : 29" X 29" PLAY AREA / OUT SIDE -34'''',THICKNESS : 3MMSURFACE : CHINESE PLYWOOD, FRAME : TREATED MAHOGANI , FRAME SIZE : 2"X 3",WEIGHT : 7KG,FREE COINS SET | STRIKER')
WHERE slug = 'champion-carrom-board';
UPDATE product SET display_order = 352
WHERE slug = 'medium-carrom-board';
UPDATE product SET display_order = 353
WHERE slug = 'baby-carrom-board';
UPDATE product SET display_order = 354,
    description = COALESCE(NULLIF(description, ''), 'SIZE : 29" X 29" PLAY AREA / OUT SIDE -34'''',SURFACE : ENGLISH BIRCH PLYWOOD,FRAME : TEAKWOOD , FRAME SIZE : 2"X 3",FREE COINS SET | STRIKER & BORIC POWDER')
WHERE slug = 'special-teak-carrom-board';
UPDATE product SET display_order = 359,
    description = COALESCE(NULLIF(description, ''), 'SIZE : 29" X 29" PLAY AREA / OUTSIDE-34'''', SURFACE : CHINESE PLYWOOD, FRAME : TREATED KOHOMBA,FRAME SIZE : 2" X 3",FREE COINS SET & STRIKER')
WHERE slug = 'tournament-carrom-board';
UPDATE product SET display_order = 362,
    description = COALESCE(NULLIF(description, ''), 'SIZE : 29" X 29" PLAY AREA / OUT SIDE -34'''',SURFACE : ENGLISH BIRCH PLYWOOD,FRAME : SATINWOOD , FRAME SIZE : 2"X 3",FREE COINS SET | STRIKER & BORIC POWDER')
WHERE slug = 'special-satin-wood-carrom-board';
UPDATE product SET display_order = 367,
    description = COALESCE(NULLIF(description, ''), 'SIZE : 29" X 29" PLAY AREA / OUT SIDE -34'''', SURFACE : ENGLISH BIRCH PLYWOOD, FRAME : IRONWOOD, FRAME SIZE : 2"X 3" FREE COINS SET | STRIKER & BORIC POWDER')
WHERE slug = 'sri-lankan-iron-wood-carrom-board';
UPDATE product SET display_order = 370,
    description = COALESCE(NULLIF(description, ''), 'STEEL : FOLDABLE, HEIGHT ADJUSTABLE ( 27INCH ) , HAMMER FINISHED WITH RUBBER BUSH')
WHERE slug = 'foldable-steel-carrom-board-stand';
UPDATE product SET display_order = 371,
    description = COALESCE(NULLIF(description, ''), 'STEEL : FOLDABLE, HEIGHT ADJUSTABLE ( 27INCH ) , NATURAL WOODEN STAND WITH RUBBER BUSH')
WHERE slug = 'foldable-wooden-carrom-board-stand';
UPDATE product SET display_order = 374,
    description = COALESCE(NULLIF(description, ''), 'Foldable wooden easel for kids with green & white double sided board. Green side to be used with chalk and white side with a white board marker Simple to assemble - complete with all fittings. Made of Wooden Material. Board Size : 21" X 17" inch, Total Easel Height : 32" X 20" inch, Weight : 2.1 kg , Pen tray dimensions : 17" x 14" inch, Height : 32 inch')
WHERE slug = 'kids-board';
UPDATE product SET display_order = 375,
    description = COALESCE(NULLIF(description, ''), 'It''s portable and light weighted. Double sided white board size is 12 x 8 inch ( A4 Size ). Thickness is 3mm. Design to work on palm. Child friendly. Whiteboard marker-compatible')
WHERE slug = 'kids-board-a4-size-white-board-double-sided';
UPDATE product SET display_order = 376,
    description = COALESCE(NULLIF(description, ''), 'It''s portable and light weighted. Double sided blcack board size is 12 x 8 inch ( A4 Size ). Thickness is 3mm. Design to work on palm. Child friendly. Chalk - compatible')
WHERE slug = 'kids-board-a4-size-black-board-double-sided';
UPDATE product SET display_order = 377,
    description = COALESCE(NULLIF(description, ''), 'It''s portable and light weighted. Double sided green board size is 12 x 8 inch ( A4 Size ). Thickness is 3mm. Design to work on palm. Child friendly. Chalk - compatible')
WHERE slug = 'kids-board-a4-size-green-board-double-sided';
UPDATE product SET display_order = 381,
    description = COALESCE(NULLIF(description, ''), 'High Quality Colorful Velvet Surface, Made With Aluminum Hooks To Hang The Keys, High Quality Aluminium Box Bar Frame With Lockable Front Glass Door. To Be Used As Key Holder. Improved Modern Design.')
WHERE slug = 'key-holder';
UPDATE product SET display_order = 393,
    description = COALESCE(NULLIF(description, ''), 'It''s Portable. Hiquality 3 white boards size 5x3 feet. Long lasting dry erase surface. Lockable caster wheels enable easy moving the partition.')
WHERE slug = 'mobile-partition-double-sided-white-board-5-x-3ft-3-panels';
UPDATE product SET display_order = 394,
    description = COALESCE(NULLIF(description, ''), 'It''s Portable. Hiquality double sided colourful 3 fabric pin boards size 5x3 feet. The Rubber sheets underneath to pin up all the notices. Long lasting and string and no AC leak. Lockable caster wheels enable easy moving the partition.')
WHERE slug = 'mobile-partition-double-sided-notice-board-5-x-3ft-3-panels';
UPDATE product SET display_order = 395,
    description = COALESCE(NULLIF(description, ''), 'It''s Portable. Hiquality colourful 3 fabric pin boards and 3 white board size 5x3 feet. The Rubber sheets underneath to pin up all the notices and white board side can write every notes using white bord marker. Long lasting and string and no AC leak. Lockable caster wheels enable easy moving the partition.')
WHERE slug = 'mobile-partition-double-sided-white-and-notice-board-5-x-3ft-3-panels';
UPDATE product SET display_order = 396,
    description = COALESCE(NULLIF(description, ''), 'It''s Portable. Hiquality 3 colourful fabric boards size 5x3 feet. Long lasting and string and no AC leak. Lockable caster wheels enable easy moving the partition.')
WHERE slug = 'partition-board-covered-with-fabric-5-x-3ft-3-panels';

-- A4 boards: the sheet added the colour to the name; slug (URL) stays the seeded one.
UPDATE product SET name = 'A4 Size White Board ( Double Sided White )'
WHERE slug = 'kids-board-a4-size-white-board-double-sided' AND name LIKE 'Kids Board A4 Size%( Double Sided )';
UPDATE product SET name = 'A4 Size Black Board ( Double Sided Black )'
WHERE slug = 'kids-board-a4-size-black-board-double-sided' AND name LIKE 'Kids Board A4 Size%( Double Sided )';
UPDATE product SET name = 'A4 Size Green Board ( Double Sided - White + Green )'
WHERE slug = 'kids-board-a4-size-green-board-double-sided' AND name LIKE 'Kids Board A4 Size%( Double Sided )';

-- Value changes on this sheet vs V36 (guarded by the seeded values):
-- Scan Carrom Men Set With Disk: Rs 875 -> Rs 800; colombo flat Rs 500 -> Rs 6,000 bill gate.
UPDATE product SET single_price_cents = 80000,
    lorry_colombo_cents = NULL, lorry_colombo_gate_cents = 600000
WHERE slug = 'sport-items-scan-carrom-men-set-with-disk' AND single_price_cents = 87500;

-- New products on this sheet (same idempotent shape as V36).
INSERT INTO product (name, slug, sku, category, category_group, price_mode,
    single_price_cents, weight_kg,
    board_size_tier, lorry_colombo_cents, lorry_suburb_cents, lorry_outer_cents,
    lorry_colombo_gate_cents, lorry_suburb_gate_cents, lorry_outer_gate_cents,
    lorry_outer_whatsapp, courier_outer_blocked, description, display_order, active)
VALUES ('Sport Items Basco Carrom Men Set', 'sport-items-basco-carrom-men-set', 'SEED-SPORTITEMSBASCOCARROMMENSET', 'Carrom Board', 'Sport / Game Boards', 'SINGLE',
    35000, 1.0,
    'UNDER_2FT', NULL, NULL, NULL,
    600000, 600000, NULL, true,
    false, 'Includes 24 carrom coins, Material: Wooden, Color: Multi', 339, true)
ON CONFLICT (slug) DO NOTHING;

-- Architectural Drawing Boards (new family; inch sizes => couriable UNDER_2FT tier;
-- outer column says 'contact whatsapp' => WhatsApp contact for outer lorry).
WITH prod AS (
    INSERT INTO product (name, slug, sku, category, category_group, price_mode,
        price_range_min_cents, price_range_max_cents, display_order, active)
    VALUES ('Architectural Drawing Board ( Mahogani Wood )', 'architectural-drawing-board-mahogani-wood', 'SEED-ARCHITECTURALDRAWINGBOARDMAHOGANIWOOD', 'Architectural Drawing Board', 'Art Supplies', 'VARIANT',
        550000, 800000, 288, true)
    ON CONFLICT (slug) DO NOTHING RETURNING id
), grp AS (
    INSERT INTO spec_group (product_id, name, price_affecting, display_order)
    SELECT id, 'Size', true, 0 FROM prod
    RETURNING id, product_id
), opts AS (
    INSERT INTO spec_option (spec_group_id, value, display_order)
    SELECT grp.id, v.value, v.ord FROM grp,
        (VALUES ('A1 - 40" x 28"',0),('A2 - 28" x 20"',1),('A3 - 20" x 14"',2)) AS v(value, ord)
    RETURNING id, spec_group_id, value
)
INSERT INTO product_variant (product_id, sku, price_cents, weight_kg,
    board_size_tier, lorry_colombo_cents, lorry_suburb_cents,
    lorry_colombo_gate_cents, lorry_suburb_gate_cents,
    lorry_outer_whatsapp, courier_outer_blocked, options_signature)
SELECT grp.product_id, 'SEED-ARCHITECTURALDRAWINGBOARDMAHOGANIWOOD' || '-' || opts.id, v.price_cents, v.weight_kg, 'UNDER_2FT',
    v.colombo_c, v.suburb_c, v.colombo_g, v.suburb_g, true, false,
    opts.id::text
FROM opts JOIN grp ON opts.spec_group_id = grp.id
JOIN (VALUES ('A1 - 40" x 28"',800000,NULL::numeric,80000,100000,NULL::bigint,NULL::bigint),('A2 - 28" x 20"',675000,NULL::numeric,80000,100000,NULL::bigint,NULL::bigint),('A3 - 20" x 14"',550000,NULL::numeric,80000,100000,NULL::bigint,NULL::bigint))
    AS v(value, price_cents, weight_kg, colombo_c, suburb_c, colombo_g, suburb_g)
    ON v.value = opts.value
ON CONFLICT (product_id, options_signature) DO NOTHING;

WITH prod AS (
    INSERT INTO product (name, slug, sku, category, category_group, price_mode,
        price_range_min_cents, price_range_max_cents, display_order, active)
    VALUES ('Architectural Drawing Board ( Plywood )', 'architectural-drawing-board-plywood', 'SEED-ARCHITECTURALDRAWINGBOARDPLYWOOD', 'Architectural Drawing Board', 'Art Supplies', 'VARIANT',
        350000, 600000, 291, true)
    ON CONFLICT (slug) DO NOTHING RETURNING id
), grp AS (
    INSERT INTO spec_group (product_id, name, price_affecting, display_order)
    SELECT id, 'Size', true, 0 FROM prod
    RETURNING id, product_id
), opts AS (
    INSERT INTO spec_option (spec_group_id, value, display_order)
    SELECT grp.id, v.value, v.ord FROM grp,
        (VALUES ('A1 - 40" x 28"',0),('A2 - 28" x 20"',1),('A3 - 20" x 14"',2)) AS v(value, ord)
    RETURNING id, spec_group_id, value
)
INSERT INTO product_variant (product_id, sku, price_cents, weight_kg,
    board_size_tier, lorry_colombo_cents, lorry_suburb_cents,
    lorry_colombo_gate_cents, lorry_suburb_gate_cents,
    lorry_outer_whatsapp, courier_outer_blocked, options_signature)
SELECT grp.product_id, 'SEED-ARCHITECTURALDRAWINGBOARDPLYWOOD' || '-' || opts.id, v.price_cents, v.weight_kg, 'UNDER_2FT',
    v.colombo_c, v.suburb_c, v.colombo_g, v.suburb_g, true, false,
    opts.id::text
FROM opts JOIN grp ON opts.spec_group_id = grp.id
JOIN (VALUES ('A1 - 40" x 28"',600000,NULL::numeric,80000,100000,NULL::bigint,NULL::bigint),('A2 - 28" x 20"',447000,NULL::numeric,80000,100000,NULL::bigint,NULL::bigint),('A3 - 20" x 14"',350000,NULL::numeric,80000,100000,NULL::bigint,NULL::bigint))
    AS v(value, price_cents, weight_kg, colombo_c, suburb_c, colombo_g, suburb_g)
    ON v.value = opts.value
ON CONFLICT (product_id, options_signature) DO NOTHING;
