-- V4 — Cart (04-cart/plan.md §2). Customer carts are RLS-scoped; guest carts live client-side.

CREATE TABLE cart (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT      NOT NULL UNIQUE REFERENCES app_user(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cart_item (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id     BIGINT      NOT NULL REFERENCES cart(id) ON DELETE CASCADE,
    product_id  BIGINT      NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    variant_id  BIGINT      REFERENCES product_variant(id) ON DELETE CASCADE,
    quantity    INTEGER     NOT NULL CHECK (quantity >= 1),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- one line per (product, variant) within a cart; different variants = different lines
    CONSTRAINT ux_cart_line UNIQUE (cart_id, product_id, variant_id)
);
CREATE INDEX ix_cart_item_cart ON cart_item(cart_id);

-- RLS backstop (global/02 §6, T-2). FORCE so the table-owner app role is ALSO subject to policy
-- (owners bypass RLS by default — without FORCE the backstop would be a no-op for our single role).
ALTER TABLE cart      ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart      FORCE  ROW LEVEL SECURITY;
ALTER TABLE cart_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart_item FORCE  ROW LEVEL SECURITY;

CREATE POLICY cart_owner ON cart
    USING (customer_id = current_setting('app.current_user_id', true)::bigint);

CREATE POLICY cart_item_owner ON cart_item
    USING (cart_id IN (
        SELECT id FROM cart WHERE customer_id = current_setting('app.current_user_id', true)::bigint
    ));
