-- V59 — Price sync to the owner's 2026-08-18 sheet update ("new mrp" column), generated by
-- backend/scripts/generate_price_update.py (see that header for scope/method). Only prices
-- change here — category/description/display order are untouched (that's V47's job).
-- Every UPDATE is guarded by the price the sheet says was current (WHERE ... = old cents),
-- the same convention V47 uses, so an admin price edit made after V47 is never clobbered —
-- it just silently no-ops for that one row instead (0 rows updated).

-- Sizes priced on the sheet but never seeded (no matching size to update):
--   glass-board-with-stand / 6 x 3: Rs 54,400.00 -> Rs 57,200.00 — size was never seeded, skipped

-- Single-priced products (17).
UPDATE product SET single_price_cents = 220000
WHERE slug = 'baby-carrom-board' AND single_price_cents = 195000;
UPDATE product SET single_price_cents = 615000
WHERE slug = 'champion-carrom-board' AND single_price_cents = 590000;
UPDATE product SET single_price_cents = 205000
WHERE slug = 'chess-board' AND single_price_cents = 190000;
UPDATE product SET single_price_cents = 355000
WHERE slug = 'chess-board-teak-wood' AND single_price_cents = 340000;
UPDATE product SET single_price_cents = 127500
WHERE slug = 'dam-board' AND single_price_cents = 120000;
UPDATE product SET single_price_cents = 297500
WHERE slug = 'dam-board-teak-wood' AND single_price_cents = 290000;
UPDATE product SET single_price_cents = 2700000
WHERE slug = 'flip-chart-with-caster-wheels' AND single_price_cents = 2500000;
UPDATE product SET single_price_cents = 525000
WHERE slug = 'foldable-steel-carrom-board-stand' AND single_price_cents = 475000;
UPDATE product SET single_price_cents = 500000
WHERE slug = 'foldable-wooden-carrom-board-stand' AND single_price_cents = 450000;
UPDATE product SET single_price_cents = 50000
WHERE slug = 'kids-board-a4-size-white-board-double-sided' AND single_price_cents = 60000;
UPDATE product SET single_price_cents = 325000
WHERE slug = 'medium-carrom-board' AND single_price_cents = 300000;
UPDATE product SET single_price_cents = 515000
WHERE slug = 'practice-carrom-board' AND single_price_cents = 490000;
UPDATE product SET single_price_cents = 80000
WHERE slug = 'sport-items-basco-carrom-men-set' AND single_price_cents = 35000;
UPDATE product SET single_price_cents = 68000
WHERE slug = 'sport-items-boric-large-60g' AND single_price_cents = 60000;
UPDATE product SET single_price_cents = 40000
WHERE slug = 'sport-items-boric-small-15g' AND single_price_cents = 35000;
UPDATE product SET single_price_cents = 65000
WHERE slug = 'sport-items-wining-disk' AND single_price_cents = 55000;
UPDATE product SET single_price_cents = 1150000
WHERE slug = 'tripod-flip-chart' AND single_price_cents = 1085000;

-- Variant (per-size) prices (190).
UPDATE product_variant pv SET price_cents = 1140000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1075000;
UPDATE product_variant pv SET price_cents = 1260000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '3 x 3'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1187500;
UPDATE product_variant pv SET price_cents = 1270000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1200000;
UPDATE product_variant pv SET price_cents = 1350000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2 1/2'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1275000;
UPDATE product_variant pv SET price_cents = 1430000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1350000;
UPDATE product_variant pv SET price_cents = 1590000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 4'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1500000;
UPDATE product_variant pv SET price_cents = 1600000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1512500;
UPDATE product_variant pv SET price_cents = 1800000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1700000;
UPDATE product_variant pv SET price_cents = 1770000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 3'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1675000;
UPDATE product_variant pv SET price_cents = 2010000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1900000;
UPDATE product_variant pv SET price_cents = 2530000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8 x 4'
WHERE p.slug = 'scan-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2400000;
UPDATE product_variant pv SET price_cents = 1350000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1150000;
UPDATE product_variant pv SET price_cents = 1800000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '3 x 3'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1750000;
UPDATE product_variant pv SET price_cents = 1550000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1500000;
UPDATE product_variant pv SET price_cents = 1850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2 1/2'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1800000;
UPDATE product_variant pv SET price_cents = 1850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1800000;
UPDATE product_variant pv SET price_cents = 2150000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 4'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2100000;
UPDATE product_variant pv SET price_cents = 2500000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2450000;
UPDATE product_variant pv SET price_cents = 2500000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2450000;
UPDATE product_variant pv SET price_cents = 2850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 3'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2800000;
UPDATE product_variant pv SET price_cents = 2850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2800000;
UPDATE product_variant pv SET price_cents = 3650000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8 x 4'
WHERE p.slug = 'scan-magnetic-white-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3600000;
UPDATE product_variant pv SET price_cents = 900000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '3'' Ft'
WHERE p.slug = 'white-board-stand-only' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 850000;
UPDATE product_variant pv SET price_cents = 950000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4'' Ft'
WHERE p.slug = 'white-board-stand-only' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 900000;
UPDATE product_variant pv SET price_cents = 1000000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5'' Ft'
WHERE p.slug = 'white-board-stand-only' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 950000;
UPDATE product_variant pv SET price_cents = 1050000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6'' Ft'
WHERE p.slug = 'white-board-stand-only' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1000000;
UPDATE product_variant pv SET price_cents = 1250000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8'' Ft'
WHERE p.slug = 'white-board-stand-only' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1200000;
UPDATE product_variant pv SET price_cents = 52000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '1 x 1'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 50000;
UPDATE product_variant pv SET price_cents = 78000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '1 x 1 1/2'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 75000;
UPDATE product_variant pv SET price_cents = 104000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 1'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 100000;
UPDATE product_variant pv SET price_cents = 156000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 1 1/2'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 150000;
UPDATE product_variant pv SET price_cents = 208000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 2'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 200000;
UPDATE product_variant pv SET price_cents = 260000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 2 1/2'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 250000;
UPDATE product_variant pv SET price_cents = 312000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 300000;
UPDATE product_variant pv SET price_cents = 468000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '3 x 3'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 600000;
UPDATE product_variant pv SET price_cents = 416000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 400000;
UPDATE product_variant pv SET price_cents = 520000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2 1/2'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 600000;
UPDATE product_variant pv SET price_cents = 624000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 600000;
UPDATE product_variant pv SET price_cents = 832000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 4'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 800000;
UPDATE product_variant pv SET price_cents = 1040000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1000000;
UPDATE product_variant pv SET price_cents = 1040000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1000000;
UPDATE product_variant pv SET price_cents = 1248000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 3'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1200000;
UPDATE product_variant pv SET price_cents = 1248000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1200000;
UPDATE product_variant pv SET price_cents = 1664000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8 x 4'
WHERE p.slug = 'scan-green-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1600000;
UPDATE product_variant pv SET price_cents = 1212000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1150000;
UPDATE product_variant pv SET price_cents = 1418000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '3 x 3'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1450000;
UPDATE product_variant pv SET price_cents = 1366000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1300000;
UPDATE product_variant pv SET price_cents = 1470000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2 1/2'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1500000;
UPDATE product_variant pv SET price_cents = 1574000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1500000;
UPDATE product_variant pv SET price_cents = 1782000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 4'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1700000;
UPDATE product_variant pv SET price_cents = 2040000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1950000;
UPDATE product_variant pv SET price_cents = 2040000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1950000;
UPDATE product_variant pv SET price_cents = 2298000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 3'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2200000;
UPDATE product_variant pv SET price_cents = 2298000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2200000;
UPDATE product_variant pv SET price_cents = 2914000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8 x 4'
WHERE p.slug = 'scan-green-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2800000;
UPDATE product_variant pv SET price_cents = 1350000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1150000;
UPDATE product_variant pv SET price_cents = 1800000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '3 x 3'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1750000;
UPDATE product_variant pv SET price_cents = 1550000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1500000;
UPDATE product_variant pv SET price_cents = 1850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2 1/2'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1800000;
UPDATE product_variant pv SET price_cents = 1850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1800000;
UPDATE product_variant pv SET price_cents = 2150000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 4'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2100000;
UPDATE product_variant pv SET price_cents = 2500000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2450000;
UPDATE product_variant pv SET price_cents = 2500000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2450000;
UPDATE product_variant pv SET price_cents = 2850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 3'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2800000;
UPDATE product_variant pv SET price_cents = 2850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2800000;
UPDATE product_variant pv SET price_cents = 3650000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8 x 4'
WHERE p.slug = 'scan-green-magnetic-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3600000;
UPDATE product_variant pv SET price_cents = 52000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '1 x 1'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 50000;
UPDATE product_variant pv SET price_cents = 78000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '1 x 1 1/2'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 75000;
UPDATE product_variant pv SET price_cents = 104000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 1'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 100000;
UPDATE product_variant pv SET price_cents = 156000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 1 1/2'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 150000;
UPDATE product_variant pv SET price_cents = 208000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 2'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 200000;
UPDATE product_variant pv SET price_cents = 312000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 300000;
UPDATE product_variant pv SET price_cents = 468000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '3 x 3'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 600000;
UPDATE product_variant pv SET price_cents = 416000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 400000;
UPDATE product_variant pv SET price_cents = 624000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 600000;
UPDATE product_variant pv SET price_cents = 832000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 4'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 800000;
UPDATE product_variant pv SET price_cents = 1040000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1000000;
UPDATE product_variant pv SET price_cents = 1248000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1200000;
UPDATE product_variant pv SET price_cents = 1664000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8 x 4'
WHERE p.slug = 'scan-black-board-alumium-frame' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1600000;
UPDATE product_variant pv SET price_cents = 315000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'five-rule-white-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 300000;
UPDATE product_variant pv SET price_cents = 630000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'five-rule-white-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 600000;
UPDATE product_variant pv SET price_cents = 375000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'five-rule-green-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 360000;
UPDATE product_variant pv SET price_cents = 750000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'five-rule-green-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 720000;
UPDATE product_variant pv SET price_cents = 375000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'five-rule-black-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 360000;
UPDATE product_variant pv SET price_cents = 750000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'five-rule-black-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 720000;
UPDATE product_variant pv SET price_cents = 2280000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'glass-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2160000;
UPDATE product_variant pv SET price_cents = 2850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'glass-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2700000;
UPDATE product_variant pv SET price_cents = 3800000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'glass-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3600000;
UPDATE product_variant pv SET price_cents = 3420000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 3'
WHERE p.slug = 'glass-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3240000;
UPDATE product_variant pv SET price_cents = 4560000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'glass-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 4320000;
UPDATE product_variant pv SET price_cents = 4180000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'glass-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3960000;
UPDATE product_variant pv SET price_cents = 5900000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'glass-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 5600000;
UPDATE product_variant pv SET price_cents = 6860000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'glass-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 6520000;
UPDATE product_variant pv SET price_cents = 8780000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8 x 4'
WHERE p.slug = 'glass-board-with-stand' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 8360000;
UPDATE product_variant pv SET price_cents = 62500
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '1 x 1'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 55000;
UPDATE product_variant pv SET price_cents = 94000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '1 x 1 1/2'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 82500;
UPDATE product_variant pv SET price_cents = 125000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 1'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 110000;
UPDATE product_variant pv SET price_cents = 250000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 2'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 220000;
UPDATE product_variant pv SET price_cents = 312500
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 2 1/2'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 275000;
UPDATE product_variant pv SET price_cents = 375000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 330000;
UPDATE product_variant pv SET price_cents = 750000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '3 x 3'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 660000;
UPDATE product_variant pv SET price_cents = 500000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 440000;
UPDATE product_variant pv SET price_cents = 750000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2 1/2'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 660000;
UPDATE product_variant pv SET price_cents = 750000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 660000;
UPDATE product_variant pv SET price_cents = 1000000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 4'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 880000;
UPDATE product_variant pv SET price_cents = 1250000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1100000;
UPDATE product_variant pv SET price_cents = 1250000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1100000;
UPDATE product_variant pv SET price_cents = 1500000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 3'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1320000;
UPDATE product_variant pv SET price_cents = 1500000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1320000;
UPDATE product_variant pv SET price_cents = 2000000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8 x 4'
WHERE p.slug = 'pin-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1760000;
UPDATE product_variant pv SET price_cents = 1650000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'sliding-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1500000;
UPDATE product_variant pv SET price_cents = 1950000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'sliding-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1780000;
UPDATE product_variant pv SET price_cents = 2650000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'sliding-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2400000;
UPDATE product_variant pv SET price_cents = 3460000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'sliding-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3150000;
UPDATE product_variant pv SET price_cents = 3900000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 4'
WHERE p.slug = 'sliding-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3550000;
UPDATE product_variant pv SET price_cents = 4180000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 3'
WHERE p.slug = 'sliding-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3800000;
UPDATE product_variant pv SET price_cents = 4850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6 x 4'
WHERE p.slug = 'sliding-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 4400000;
UPDATE product_variant pv SET price_cents = 5900000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '8 x 4'
WHERE p.slug = 'sliding-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 5400000;
UPDATE product_variant pv SET price_cents = 1870000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'front-door-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1700000;
UPDATE product_variant pv SET price_cents = 2300000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'front-door-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2100000;
UPDATE product_variant pv SET price_cents = 3025000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'front-door-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2750000;
UPDATE product_variant pv SET price_cents = 3500000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'front-door-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3450000;
UPDATE product_variant pv SET price_cents = 2100000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'shock-door-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1900000;
UPDATE product_variant pv SET price_cents = 2550000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'shock-door-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2300000;
UPDATE product_variant pv SET price_cents = 3250000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 3'
WHERE p.slug = 'shock-door-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2950000;
UPDATE product_variant pv SET price_cents = 4000000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '5 x 3'
WHERE p.slug = 'shock-door-glass-notice-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3650000;
UPDATE product_variant pv SET price_cents = 650000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 1 1/2'
WHERE p.slug = 'single-side-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 550000;
UPDATE product_variant pv SET price_cents = 850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 2 1/2'
WHERE p.slug = 'single-side-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 750000;
UPDATE product_variant pv SET price_cents = 1100000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 2 1/2 (Teak)'
WHERE p.slug = 'single-side-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1000000;
UPDATE product_variant pv SET price_cents = 900000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'single-side-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 800000;
UPDATE product_variant pv SET price_cents = 1000000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'single-side-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 900000;
UPDATE product_variant pv SET price_cents = 1200000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 1 1/2'
WHERE p.slug = 'dual-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1050000;
UPDATE product_variant pv SET price_cents = 1400000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 2 1/2'
WHERE p.slug = 'dual-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1250000;
UPDATE product_variant pv SET price_cents = 1750000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 2 1/2 (Teak)'
WHERE p.slug = 'dual-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1600000;
UPDATE product_variant pv SET price_cents = 1550000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 x 3'
WHERE p.slug = 'dual-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1400000;
UPDATE product_variant pv SET price_cents = 1700000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'dual-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1550000;
UPDATE product_variant pv SET price_cents = 1075000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '3 x 2'
WHERE p.slug = 'double-side-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 975000;
UPDATE product_variant pv SET price_cents = 1325000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 x 2'
WHERE p.slug = 'double-side-menu-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1225000;
UPDATE product_variant pv SET price_cents = 1550000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6mm'
WHERE p.slug = 'special-teak-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1450000;
UPDATE product_variant pv SET price_cents = 1750000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '9mm'
WHERE p.slug = 'special-teak-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1650000;
UPDATE product_variant pv SET price_cents = 1950000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '12mm'
WHERE p.slug = 'special-teak-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1850000;
UPDATE product_variant pv SET price_cents = 2150000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '15mm'
WHERE p.slug = 'special-teak-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2050000;
UPDATE product_variant pv SET price_cents = 2450000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '18mm'
WHERE p.slug = 'special-teak-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2300000;
UPDATE product_variant pv SET price_cents = 850000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6mm'
WHERE p.slug = 'tournament-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 900000;
UPDATE product_variant pv SET price_cents = 1050000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '9mm'
WHERE p.slug = 'tournament-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1000000;
UPDATE product_variant pv SET price_cents = 1150000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '12mm'
WHERE p.slug = 'tournament-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1100000;
UPDATE product_variant pv SET price_cents = 1550000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '6mm'
WHERE p.slug = 'special-satin-wood-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1450000;
UPDATE product_variant pv SET price_cents = 1750000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '9mm'
WHERE p.slug = 'special-satin-wood-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1650000;
UPDATE product_variant pv SET price_cents = 1950000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '12mm'
WHERE p.slug = 'special-satin-wood-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1850000;
UPDATE product_variant pv SET price_cents = 2150000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '15mm'
WHERE p.slug = 'special-satin-wood-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2050000;
UPDATE product_variant pv SET price_cents = 2450000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '18mm'
WHERE p.slug = 'special-satin-wood-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2300000;
UPDATE product_variant pv SET price_cents = 2800000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '12mm'
WHERE p.slug = 'sri-lankan-iron-wood-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2600000;
UPDATE product_variant pv SET price_cents = 3100000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '15mm'
WHERE p.slug = 'sri-lankan-iron-wood-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2900000;
UPDATE product_variant pv SET price_cents = 3700000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '18mm'
WHERE p.slug = 'sri-lankan-iron-wood-carrom-board' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3500000;
UPDATE product_variant pv SET price_cents = 1300000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 X 1 ft ( 10 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1175000;
UPDATE product_variant pv SET price_cents = 1460000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 X 1 ft ( 15 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1325000;
UPDATE product_variant pv SET price_cents = 1630000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 X 1 1/2 ft ( 20 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1480000;
UPDATE product_variant pv SET price_cents = 1800000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 X 1 1/2 ft ( 25 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1635000;
UPDATE product_variant pv SET price_cents = 1970000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 1/2 X 1 1/2 ft ( 30 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1790000;
UPDATE product_variant pv SET price_cents = 2140000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 1/2 X 1 1/2 ft ( 35 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 1940000;
UPDATE product_variant pv SET price_cents = 2310000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 X 3 ft ( 40 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2095000;
UPDATE product_variant pv SET price_cents = 2475000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 X 3 ft ( 45 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2250000;
UPDATE product_variant pv SET price_cents = 2820000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '2 X 3 ft ( 50 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 2560000;
UPDATE product_variant pv SET price_cents = 3650000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = '4 X 2 1/2 ft ( 90 keys )'
WHERE p.slug = 'key-holder' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 3320000;
UPDATE product_variant pv SET price_cents = 5940000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = 'Double Sided White Board 5 x 3ft ( 3 Panels )'
WHERE p.slug = 'mobile-partition-double-sided-white-board-5-x-3ft-3-panels' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 5400000;
UPDATE product_variant pv SET price_cents = 7430000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = 'Double Sided Notice Board 5 x 3ft ( 3 Panels )'
WHERE p.slug = 'mobile-partition-double-sided-notice-board-5-x-3ft-3-panels' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 6750000;
UPDATE product_variant pv SET price_cents = 7180000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = 'Double Sided White and Notice Board 5 x 3ft ( 3 Panels )'
WHERE p.slug = 'mobile-partition-double-sided-white-and-notice-board-5-x-3ft-3-panels' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 6525000;
UPDATE product_variant pv SET price_cents = 5720000
FROM product p JOIN spec_group sg ON sg.product_id = p.id AND sg.price_affecting
JOIN spec_option so ON so.spec_group_id = sg.id AND so.value = 'Partition board covered with Fabric 5 x 3ft ( 3 Panels )'
WHERE p.slug = 'partition-board-covered-with-fabric-5-x-3ft-3-panels' AND pv.product_id = p.id
  AND pv.options_signature = so.id::text AND pv.price_cents = 5200000;

-- Legacy size labels that don't textually match this sheet (matched by the product's unique old price instead; one statement per product so the whole old->new price map is matched against a single before-update snapshot).
UPDATE product_variant pv SET price_cents = v.new_c
FROM product p, (VALUES (37500,40000), (56250,60000), (75000,80000), (84375,90000), (112500,120000), (140625,150000), (150000,160000), (168750,180000), (187500,200000), (225000,240000), (234375,250000), (281250,300000), (337500,360000), (300000,320000), (375000,400000), (450000,480000), (600000,640000), (562500,600000), (750000,800000), (675000,720000), (900000,960000), (1200000,1280000)) AS v(old_c, new_c)
WHERE p.slug = 'scan-white-board' AND pv.product_id = p.id AND pv.price_cents = v.old_c;

-- Refresh denormalized price_range_* for every VARIANT product touched above.
UPDATE product p SET
    price_range_min_cents = sub.min_c,
    price_range_max_cents = sub.max_c
FROM (SELECT product_id, MIN(price_cents) AS min_c, MAX(price_cents) AS max_c
      FROM product_variant WHERE active GROUP BY product_id) sub
WHERE p.id = sub.product_id AND p.price_mode = 'VARIANT'
  AND p.slug IN ('double-side-menu-board', 'dual-menu-board', 'five-rule-black-board', 'five-rule-green-board', 'five-rule-white-board', 'front-door-glass-notice-board', 'glass-board', 'glass-board-with-stand', 'key-holder', 'mobile-partition-double-sided-notice-board-5-x-3ft-3-panels', 'mobile-partition-double-sided-white-and-notice-board-5-x-3ft-3-panels', 'mobile-partition-double-sided-white-board-5-x-3ft-3-panels', 'partition-board-covered-with-fabric-5-x-3ft-3-panels', 'pin-board', 'scan-black-board-alumium-frame', 'scan-green-board-alumium-frame', 'scan-green-board-with-stand', 'scan-green-magnetic-board-with-stand', 'scan-magnetic-white-board-with-stand', 'scan-white-board', 'scan-white-board-with-stand', 'shock-door-glass-notice-board', 'single-side-menu-board', 'sliding-glass-notice-board', 'special-satin-wood-carrom-board', 'special-teak-carrom-board', 'sri-lankan-iron-wood-carrom-board', 'tournament-carrom-board', 'white-board-stand-only');
