-- V5 — Orders (09-orders/plan.md §2). Immutable financial records with snapshotted lines.
-- Built before checkout (V6) since checkout creates order drafts; no FK between them.

CREATE TABLE "order" (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number     VARCHAR(40)  NOT NULL UNIQUE,                 -- SL-YYYYMMDD-rand-sig (verifiable)
    customer_id      BIGINT       REFERENCES app_user(id) ON DELETE SET NULL,  -- null = guest
    guest_email      VARCHAR(254),
    contact_name     VARCHAR(160) NOT NULL,
    contact_phone    VARCHAR(32)  NOT NULL,
    contact_email    VARCHAR(254) NOT NULL,
    fulfilment_type  VARCHAR(16)  NOT NULL CHECK (fulfilment_type IN ('DELIVERY','PICKUP_SHOP','PICKUP_FACTORY')),
    ship_street      VARCHAR(300),
    ship_city        VARCHAR(120),
    ship_province    VARCHAR(120),
    ship_postal_code VARCHAR(10),
    -- billing snapshot (always asked — BA-6)
    bill_name        VARCHAR(200),
    bill_tax_id      VARCHAR(60),
    bill_street      VARCHAR(300),
    bill_city        VARCHAR(120),
    bill_province    VARCHAR(120),
    bill_postal_code VARCHAR(10),
    -- money (LKR cents)
    subtotal_cents     BIGINT NOT NULL CHECK (subtotal_cents >= 0),
    discount_cents     BIGINT NOT NULL DEFAULT 0,        -- expansion hook (FR-ORDER-27)
    delivery_cents     BIGINT NOT NULL DEFAULT 0,
    tax_cents          BIGINT NOT NULL DEFAULT 0,
    total_cents        BIGINT NOT NULL CHECK (total_cents >= 0),
    delivery_payment   VARCHAR(10) NOT NULL DEFAULT 'PREPAID' CHECK (delivery_payment IN ('PREPAID','COD')),
    delivery_cod_cents BIGINT NOT NULL DEFAULT 0,
    -- shipment tracking hook (FR-ORDER-13)
    carrier          VARCHAR(80),
    tracking_ref     VARCHAR(120),
    status           VARCHAR(28) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at TIMESTAMPTZ, confirmed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_order_customer ON "order"(customer_id);
CREATE INDEX ix_order_status   ON "order"(status);

CREATE TABLE order_item (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT       NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    product_id       BIGINT       REFERENCES product(id)         ON DELETE SET NULL,  -- snapshot survives delete
    variant_id       BIGINT       REFERENCES product_variant(id) ON DELETE SET NULL,
    sku_snapshot     VARCHAR(64)  NOT NULL,
    name_snapshot    VARCHAR(300) NOT NULL,
    handling_class_snapshot VARCHAR(16),
    unit_price_cents BIGINT       NOT NULL CHECK (unit_price_cents >= 0),
    quantity         INTEGER      NOT NULL CHECK (quantity >= 1),
    line_total_cents BIGINT       NOT NULL CHECK (line_total_cents >= 0)
);
CREATE INDEX ix_order_item_order ON order_item(order_id);

CREATE TABLE order_status_event (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT      NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    from_status VARCHAR(28),
    to_status   VARCHAR(28) NOT NULL,
    actor_type  VARCHAR(10) NOT NULL CHECK (actor_type IN ('SYSTEM','ADMIN','CUSTOMER')),
    actor_id    BIGINT,
    note        VARCHAR(300),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_order_event_order ON order_status_event(order_id);

-- Orders are read by owner (customer), guest (by order#+email), AND admin (all) — so a simple
-- owner-only FORCE policy would block guest/admin reads. The full multi-context RLS (customer +
-- guest + admin GUCs) lands with the admin phase (01_SECURITY_PLAN B4). For now the PRIMARY control
-- is the app-layer ownership check (queries filter by customer_id); RLS is ENABLEd as scaffolding.
ALTER TABLE "order" ENABLE ROW LEVEL SECURITY;
CREATE POLICY order_owner ON "order"
    USING (customer_id = current_setting('app.current_user_id', true)::bigint);
