-- V6 — Checkout & delivery config (05-checkout-delivery). Admin-managed in Phase 7; read at checkout.
-- Money in LKR cents. Seeds sane defaults so checkout works immediately.

CREATE TABLE delivery_zone (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(120) NOT NULL,
    base_charge_cents  BIGINT       NOT NULL DEFAULT 0 CHECK (base_charge_cents >= 0),
    per_kg_charge_cents BIGINT      NOT NULL DEFAULT 0 CHECK (per_kg_charge_cents >= 0),
    fuel_pct           NUMERIC(5,2) NOT NULL DEFAULT 0,
    active             BOOLEAN      NOT NULL DEFAULT true
);

CREATE TABLE delivery_zone_postal_code (
    postal_code VARCHAR(10) PRIMARY KEY,             -- one zone per code (overlap impossible, FR-ADMIN-2)
    zone_id     BIGINT NOT NULL REFERENCES delivery_zone(id) ON DELETE CASCADE
);

CREATE TABLE delivery_config (
    id                     INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),  -- singleton
    pick_first_cents       BIGINT NOT NULL DEFAULT 0,
    pick_next_cents        BIGINT NOT NULL DEFAULT 0,
    fragile_surcharge_cents BIGINT NOT NULL DEFAULT 0,
    oversize_surcharge_cents BIGINT NOT NULL DEFAULT 0,
    dim_divisor            INTEGER NOT NULL DEFAULT 6000
);

CREATE TABLE tax_config (
    id        INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),    -- singleton
    rate_bps  INTEGER NOT NULL DEFAULT 0 CHECK (rate_bps >= 0), -- basis points (e.g. 800 = 8%)
    label     VARCHAR(60) NOT NULL DEFAULT 'Tax'
);

-- Seed defaults (admin tunes later in Phase 7).
INSERT INTO delivery_config (id, pick_first_cents, pick_next_cents, fragile_surcharge_cents, oversize_surcharge_cents)
    VALUES (1, 0, 0, 25000, 30000);           -- fragile +Rs250, oversize +Rs300
INSERT INTO tax_config (id, rate_bps, label) VALUES (1, 0, 'Tax');

INSERT INTO delivery_zone (id, name, base_charge_cents, per_kg_charge_cents)
    VALUES (1, 'Colombo Metro', 50000, 8000);  -- Rs500 base + Rs80/kg
INSERT INTO delivery_zone_postal_code (postal_code, zone_id) VALUES
    ('00100', 1), ('00400', 1), ('10100', 1), ('10250', 1);
