-- V7 — Payments (06-payments/plan.md §2). PAID only on verified gateway notify; idempotent.

CREATE TABLE payment (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT      NOT NULL UNIQUE REFERENCES "order"(id) ON DELETE CASCADE,
    method              VARCHAR(20) NOT NULL CHECK (method IN ('PAYHERE','BANK_TRANSFER')),
    status              VARCHAR(28) NOT NULL CHECK (status IN
                          ('PENDING','PAID','FAILED','AWAITING_BANK_CONFIRMATION','BANK_REJECTED')),
    online_amount_cents BIGINT      NOT NULL CHECK (online_amount_cents >= 0),
    currency            VARCHAR(3)  NOT NULL DEFAULT 'LKR',
    gateway_payment_id  VARCHAR(120),
    gateway_status_code VARCHAR(8),
    confirmed_at        TIMESTAMPTZ,
    confirmed_by        BIGINT REFERENCES app_user(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE bank_transfer_slip (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id    BIGINT       NOT NULL REFERENCES payment(id) ON DELETE CASCADE,
    storage_key   VARCHAR(512) NOT NULL,
    url           VARCHAR(1024) NOT NULL,
    slip_hash     VARCHAR(64)  NOT NULL,
    review_status VARCHAR(12)  NOT NULL DEFAULT 'PENDING' CHECK (review_status IN ('PENDING','CONFIRMED','REJECTED')),
    review_note   VARCHAR(300),
    reviewed_by   BIGINT REFERENCES app_user(id),
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_slip_hash ON bank_transfer_slip(slip_hash);

-- Idempotency + audit for gateway callbacks: the same event is processed exactly once (T-4).
CREATE TABLE payment_event (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider     VARCHAR(20) NOT NULL,
    external_ref VARCHAR(120) NOT NULL,
    status_code  VARCHAR(8),
    signature_ok BOOLEAN     NOT NULL,
    processed    BOOLEAN     NOT NULL DEFAULT false,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_payment_event UNIQUE (provider, external_ref, status_code)
);
