-- V8 — Notifications outbox (10-notifications/plan.md §2). Enqueue in-txn, send async, idempotent.
CREATE TABLE notification (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(40)  NOT NULL,
    recipient       VARCHAR(254) NOT NULL,
    subject         VARCHAR(300) NOT NULL,
    body            TEXT         NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL UNIQUE,    -- replay-safe (FR-NOTIFY-4)
    status          VARCHAR(12)  NOT NULL DEFAULT 'PENDING'
                      CHECK (status IN ('PENDING','SENT','RETRYING','FAILED')),
    attempts        INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    last_error      VARCHAR(500),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    sent_at         TIMESTAMPTZ
);
CREATE INDEX ix_notification_due ON notification(status, next_attempt_at)
    WHERE status IN ('PENDING','RETRYING');
