-- V9 — Admin settings + audit (08-admin-dashboard/plan.md §2).
CREATE TABLE app_setting (
    key        VARCHAR(60) PRIMARY KEY,        -- 'cod_enabled','bank_transfer_enabled','bank_account_details'…
    value      TEXT        NOT NULL,
    updated_by BIGINT      REFERENCES app_user(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE admin_audit_log (                  -- governance (NFR-ADMIN-1, SEC-ADMIN-2)
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id   BIGINT      NOT NULL REFERENCES app_user(id),
    action     VARCHAR(60) NOT NULL,
    entity     VARCHAR(60),
    entity_id  VARCHAR(60),
    before     TEXT,
    after      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_admin ON admin_audit_log(admin_id, created_at);

-- payment-method toggles consumed by checkout/payments (06/08)
INSERT INTO app_setting (key, value) VALUES ('cod_enabled', 'true'), ('bank_transfer_enabled', 'true');
